vmware/ansible-vsphere-gos-validation

README.md
docker_file/Dockerfile

Fixes new feature request #4, add a new Dockerfile and generated docker image, push it to docker hub for users downloading and testing.

[New Feature] Add Dockerfile and update it in README file

---

common/vm_wait_power_state.yml
plugin/ansible_vsphere_gosv_log.py

Fixes #23 This fix added condition check for checking dict attribute `instance` is defined at firstly

Check dict attribute is defined before using it

---

windows/cpu_hot_add_basic/cpu_hot_add_test_client.yml

Fix cpu_hotadd_num_list varaible name error

---

windows/setup/test_setup.yml
windows/utils/win_set_powercfg.yml

Add win_set_powercfg.yml in Windows test setup

---

README.md

#38 Modify readme to add support of ubuntu 21.04
Signed-off-by: ZouYuhua <zouy@vmware.com>

Modify readme to add support of ubuntu 21.04

---

linux/open_vm_tools/get_install_uninstall_cmd.yml
linux/utils/add_repo_from_baseurl.yml

```
| Product | Version | Build    | Hostname or IP |
| vCenter | 7.0.0   | 15952599 | 10.161.70.9    |
| ESXi    | 7.0.0   | 15843807 | 10.161.64.255  |
| VM Name             | test_vm                       |
| VM IP               | 10.161.68.45                  |
| Guest OS Type       | RedHat 8.4 x86_64             |
| VM Tools …
```

Update ovt install/uninstall command

---

linux/deploy_vm/templates/ubuntu-iso-user-data.j2
linux/deploy_vm/ubuntu/reconfigure_ubuntu_iso_vm.yml
linux/utils/create_seed_iso.yml

Fix #54 
Update ubuntu auotinstall config with network settings, and update proxy with 'http' prefix.

Fix ubuntu autoinstall issue

---

windows/cpu_hot_add_basic/cpu_hot_add_prepare.yml

Add wait for winrm connectable after VM power on in cpu_hot_add_basic

---

windows/guest_customization/check_guest_reset_time.yml
windows/guest_customization/gosc_sanity_dhcp.yml
windows/guest_customization/gosc_sanity_staticip.yml

Add check_guest_reset_time.yml for Windows on 6.5 ESXi host

---

changelogs/changelog.yml

Add changelog file for release 1.1

---

windows/deploy_vm/create_unattend_install_iso.yml

Add use_proxy parameter in get_url module

---

docker_file/Dockerfile
requirements.txt
requirements.yml

Update requirements files

---

common/vm_hot_add_ctrl_disk.yml
linux/vhba_hot_add_remove/hot_add_remove_disk.yml
linux/vhba_hot_add_remove/vhba_device_hot_add_remove.yml
linux/vhba_hot_add_remove/wait_device_list_changed.yml
windows/vhba_hot_add_remove/hotadd_vm_disk_new_ctrl.yml

Test results:
```
- - 'VCENTER: 6.5.0 14020092'
- 'ESXI: 6.5.0 Update 3 13932383'
- 'GUEST OS: SLES 15.3 x86_64'
- 'VMTOOLS: 11.2.5.26209 (build-17337674)'
- 'Results: PASS (7/7) in 01:10:26.'
- ' * deploy_vm_efi_paravirtual_vmxnet3.....................................Passed'
- ' * check_inbox_driver....................................................Passed'
- ' * paravirtual_vhba_device_ops...........................................Passed'
- ' * lsilogic_vhba_device_ops..............................................Passed'
- ' * lsilogicsas_vhba_device_ops...........................................Passed'
- ' * sata_vhba_device_ops..................................................Passed'
- ' * nvme_vhba_device_ops..................................................Passed'
- - 'VCENTER: …
```

Add tasks to test hot adding disk and controller at the same time

---

windows/vhba_hot_add_remove/hotadd_vm_disk_existing_ctrl.yml
windows/vhba_hot_add_remove/hotadd_vm_disk_new_ctrl.yml
windows/vhba_hot_add_remove/hotremove_vm_disk_ctrl.yml

Add wait 10 seconds after controller and disk hotadd

---

linux/deploy_vm/check_configured_cdrom_iso.yml

Handle space in OS ISO path situation

---

common/vm_check_snapshot_exist.yml
windows/guest_customization/gosc_sanity_dhcp.yml
windows/guest_customization/gosc_sanity_staticip.yml
windows/guest_customization/win_gosc_cleanup.yml
windows/guest_customization/win_gosc_prepare.yml
windows/setup/base_snapshot_check_revert.yml
windows/setup/test_setup.yml
windows/setup/win_guest_reconfig.yml
windows/utils/win_check_file_exist.yml
windows/utils/win_disable_store_auto_update.yml
windows/utils/win_get_file.yml
windows/utils/win_get_sub_files_folders.yml
windows/utils/win_is_folder.yml

Fix GOSC issue and always get GOSC log files

---

windows/deploy_vm/deploy_vm.yml

Increase Windows install timeout value to adjust to high latency env

---

env_setup/env_setup.yml
env_setup/get_ansible_info.yml

Add getting installed Ansible and collections info

---

common/esxi_get_version_build.yml
common/vm_take_snapshot.yml
windows/check_os_fullname/check_os_fullname.yml
windows/check_quiesce_snapshot/check_quiesce_snapshot.yml
windows/check_quiesce_snapshot/check_vmx_disk_enable_uuid.yml
windows/check_quiesce_snapshot/collect_vss_logs.yml
windows/setup/base_snapshot_check_revert.yml
windows/setup/test_setup.yml
windows/utils/win_check_winrm.yml
windows/utils/win_enable_vss_log.yml

Add enable vss log and get event logs from Windows guest 

---

common/vm_get_mem_info.yml

Correct the path to vm_get_config.yml in common/vm_get_mem_info.yml

Correct common task path to vm_get_config.yml

---

windows/check_quiesce_snapshot/check_custom_scripts_executed.yml
windows/check_quiesce_snapshot/check_quiesce_snapshot.yml
windows/check_quiesce_snapshot/collect_vss_logs.yml
windows/guest_customization/check_autologon_count.yml
windows/utils/win_enable_vss_log.yml
windows/utils/win_wait_file_exist.yml

Fix Windows quiesce snapshot and gosc test case issue

---

common/README.md
common/vm_get_guest_info.yml
linux/setup/test_setup.yml
linux/setup/vm_guest_ip_get_save.yml
plugin/ansible_vsphere_gosv_log.py
windows/setup/test_setup.yml

Gather guest id, guest full name and guest detailed data in guest info, and print them in results.log

Fix 114 Collect guest info in result.log

---

common/vm_get_vmtools_status.yml
windows/mouse_driver_vmtools/mouse_driver_vmtools.yml
windows/network_device_ops/network_adapter_deviceops.yml
windows/utils/win_get_netadapter_num.yml
windows/wintools_uninstall_verify/uninstall_vmtools.yml

Add check dict attribute of task result in win_get_netadapter_num.yml

---

common/vm_get_ip.yml
common/vm_get_vmtools_status.yml
linux/setup/test_setup.yml
windows/check_ip_address/check_ip_address.yml
windows/check_os_fullname/check_os_fullname.yml
windows/check_quiesce_snapshot/check_quiesce_snapshot.yml
windows/guest_customization/gosc_sanity_dhcp.yml
windows/guest_customization/gosc_sanity_staticip.yml
windows/mouse_driver_vmtools/mouse_driver_vmtools.yml
windows/network_device_ops/vmxnet3_network_device_ops.yml
windows/setup/test_setup.yml
windows/stat_balloon/stat_balloon.yml
windows/utils/shutdown_vm.yml
windows/vgauth_check_service/vgauth_check_service.yml
windows/vhba_hot_add_remove/paravirtual_vhba_device_ops.yml
windows/wintools_complete_install_verify/wintools_complete_install_verify.yml
windows/wintools_uninstall_verify/wintools_uninstall_verify.yml

For fixing issue #138 remove tools status initialize firstly, then I'll do some changes on this in next release.

Remove initializing tools status 

---

README.md
changelogs/changelog.yml

Will update with the latest released and supported OS versions in README.

Add changelog for v1.2 release

---

windows/setup/win_guest_reconfig.yml

[Windows] Change using wmic command to powershell command

---

linux/deploy_vm/deploy_vm_from_iso.yml

Firmware should be efi when enable secureboot

---

linux/guest_customization/linux_gosc_workflow.yml
linux/utils/get_guest_ovt_version_build.yml

```
- - 'VCENTER: 6.7.0 8170161'
- 'ESXI: 6.7.0 8169922'
- 'GUEST OS: VMware Photon OS 4.0 x86_64'
- 'VMTOOLS: 11.3.5.31214 (build-18557794)'
- 'Hardware Version: vmx-14'
- 'Results: PASS (26/28), FAIL (1/28), NO RUN(1/28) in 01:27:50.'
- ' * deploy_vmwarephoton_ova...............................................Passed'
- ' * ovt_verify_install....................................................Passed'
- ' * ovt_verify_status.....................................................Passed'
- ' * vgauth_check_service..................................................Passed'
- ' * check_ip_address......................................................Passed'
- ' * stat_balloon..........................................................Passed'
- ' * …
```

Install open-vm-tools-gosc for Photon OS 4.0 before GOSC

---

autoinstall/RHEL/8/server_with_GUI/ks.cfg
autoinstall/RHEL/8/server_without_GUI/ks.cfg
autoinstall/SLE/15/SP3/SLED/autoinst.xml
autoinstall/SLE/15/SP3/SLES/autoinst.xml
autoinstall/SLE/15/SP3/SLES_Minimal/autoinst.xml
autoinstall/SLE/15/SP4/SLED/autoinst.xml
common/nfs_mount.yml
common/ovf_export.yml
common/vm_set_guest_id.yml
linux/deploy_vm/amazonlinux/reconfigure_amazonlinux_vm.yml
linux/deploy_vm/photon/reconfigure_photon_vm.yml
linux/deploy_vm/templates/photon-user-data.j2
linux/utils/add_official_online_repo.yml
linux/utils/add_repo_from_baseurl.yml

Update autoinstall configs for internal testing

---

README.md
docs/KNOWN_ISSUES.md

Add known issue of Windows 11

---

.github/workflows/github-actions-copyright.yml

Add change copyright action

---

vars/test.yml
windows/deploy_vm/create_unattend_install_iso.yml
windows/deploy_vm/deploy_vm.yml
windows/deploy_vm/get_inbox_driver_info.yml
windows/utils/win_get_device_driver.yml

[Windows] Add a new parameter windows_has_inbox_driver to use inbox pvscsi driver

---

common/add_host_in_memory_inventory.yml
env_setup/env_setup.yml
vars/test.yml

Add a new variable esxi_shell which allows user to set ESXi default shell. By default, ESXi shell is "/bin/sh"
```
+---------------------------------------------------------------+
| VMTools Version           | 11.3.5.31214 (build-18557794)     |
+---------------------------------------------------------------+
| CloudInit Version         | 21.4                              |
+---------------------------------------------------------------+
| Config Guest Id           | vmwarePhoton64Guest               |
+---------------------------------------------------------------+
| GuestInfo Guest Id        | vmwarePhoton64Guest               |
+---------------------------------------------------------------+
| GuestInfo Guest Full Name | VMware Photon OS (64-bit)         | …
```

Add variable esxi_shell for setting default shell on ESXi server

---

linux/check_os_fullname/almalinux_fullname_map.yml
linux/check_os_fullname/check_os_fullname.yml
linux/check_os_fullname/rocky_fullname_map.yml
plugin/ansible_vsphere_gosv_log.py

Fix #223 Fix guest full name for AlmaLinux and Rocky Linux

Add os fullname for AlmaLinux and Rocky Linux

---

linux/check_os_fullname/oraclelinux_fullname_map.yml

Fix #261 oracle linux guest full name mapping on ESXi 6.5

---

linux/open_vm_tools/ovt_verify_install.yml

Fix #250 Exit tests when ovt_verify_install fails

---

linux/guest_customization/gosc_support_matrix.yml

Add RHEL 9.0 into GOSC support matrix

---

common/vm_wait_log_msg.yml
linux/deploy_vm/deploy_vm_from_iso.yml
windows/deploy_vm/deploy_vm.yml

Fix #116 Add keyword checking for secureboot image approved at deploy_vm

---

README.md
autoinstall/Ubuntu/Server/user-data.j2
common/vm_get_ip_from_vmtools.yml
common/vm_wait_ping.yml
linux/deploy_vm/create_unattend_install_iso.yml
linux/deploy_vm/deploy_vm.yml
linux/deploy_vm/deploy_vm_from_iso.yml
linux/deploy_vm/eject_del_unattend_install_iso.yml
linux/deploy_vm/get_boot_images_from_iso.yml
linux/deploy_vm/rebuild_unattend_install_iso.yml
linux/deploy_vm/ubuntu/ubuntu_install_os.yml
linux/network_device_ops/enable_new_ethernet.yml
linux/utils/add_official_online_repo.yml
linux/utils/repo_update.yml
linux/vhba_hot_add_remove/vhba_device_hot_add_remove.yml
linux/vhba_hot_add_remove/wait_device_list_changed.yml

Fix Ubuntu autoinstall failure at waiting for cloud-init timeout

---

linux/setup/reconfig_existing_guest.yml

Fix the issue that PackageKit failed to be uninstalled due to locked process

---

linux/utils/add_extra_online_repo.yml

```
+-------------------------------------------------------------------------+
| Guest OS Distribution     | Debian 11.3 i386                            |
+-------------------------------------------------------------------------+
| CloudInit Version         |                                             |
+-------------------------------------------------------------------------+
| GUI Installed             | True                                        |
+-------------------------------------------------------------------------+
| Config Guest Id           | debian11Guest                               |
+-------------------------------------------------------------------------+
| GuestInfo Guest Id        | debian11Guest                               | …
```

Support to add Debian 32bit repo

---

linux/check_os_fullname/rocky_fullname_map.yml

Update tools version for getting expected Rocky Linux full name

---

common/test_rescue.yml

Correct relative path for common tasks used in test_rescue.yml

---

linux/guest_customization/gosc_support_matrix.yml

Support to test RHEL 9.0 perl GOSC on VC 6.7 Update 3r

---

linux/guest_customization/gosc_support_matrix.yml

```
| Product | Version | Build    | Hostname or IP |
| vCenter | 7.0.3   | 20051473 | 
| ESXi    | 7.0.3   | 20036589 | 
+------------------------------------------------------------------------------+
| Name                      | test_rhel9                                       |
+------------------------------------------------------------------------------+
| Guest OS Distribution     | RedHat 9.0 x86_64                                |
+--------------------------------------------------------------------------- …
```

Update GOSC testing support matrix for RHEL 9.0 on 7.0U3f

---

windows/wintools_uninstall_verify/check_vmxnet3_inbox_loaded.yml

change the known issue condition of VMware Tools version for case uninstall tools. 

change the known issue condition of VMware Tools version

---

common/README.md
common/vm_enable_nested_virtual.yml
common/vm_set_nested_virtual.yml

Add common task to enable CPU nested virtualization

---

common/local_mount.yml
common/local_unmount.yml
linux/utils/add_local_dvd_repo.yml
linux/utils/eject_cdrom_in_guest.yml

Signed-off-by: ZouYuhua <zouy@vmware.com>
Fix issue: couldn't resolve module/action 'mount'
pass for the testing:

module name "mount" to "ansible.posix.mount"

---

windows/vhba_hot_add_remove/paravirtual_vhba_device_ops.yml

[Windows]fix undefine error for pvscsi case

---

windows/wsl_distro_install_uninstall/check_wsl_version.yml
windows/wsl_distro_install_uninstall/install_wsl.yml
windows/wsl_distro_install_uninstall/wsl_distro_install_uninstall.yml
windows/wsl_distro_install_uninstall/wsl_test_prepare.yml

Since inbox version of WSL is removed from 25267, modify the case to install store verson of WSL from build 25267

[Windows]Install store version of WSL from Windows build 25267

---

windows/wsl_distro_install_uninstall/install_wsl.yml
windows/wsl_distro_install_uninstall/wsl_distro_install_uninstall.yml

[Windows]wsl for windows server

---

common/esxi_get_host_facts.yml
linux/stat_hosttime/stat_hosttime.yml
windows/gosv_testcase_list.yml
windows/stat_hosttime/stat_hosttime.yml

Add a new test case stat_hosttime for Windows. 
btw: Improve the existing test case stat_hosttime for Linux.

Add new test case stat_hosttime for Windows

---

README.md
common/README.md
common/test_rescue.yml
common/vm_get_ip_from_vmtools.yml
common/vm_get_primary_nic.yml
common/vm_test_nic.yml
common/vm_wait_guest_ip.yml
env_setup/check_vm_settings.yml

Changed the waiting guest IP from guest info summary to guest property of vSphere schema.

Fix waiting IPv4 address failure when hw_eth0.ipaddresses is null

---

autoinstall/FreeBSD/installerconfig
common/test_rescue.yml
linux/deploy_vm/create_unattend_install_iso.yml
linux/deploy_vm/deploy_vm_from_iso.yml
linux/deploy_vm/eject_del_unattend_install_iso.yml
linux/deploy_vm/rebuild_unattend_install_iso.yml
linux/utils/shutdown.yml

New feature: suppport unattended install for freebsd
Test result:

[FreeBSD] suppport unattended install for freebsd

---

autoinstall/README.md

modify README file to add note about freeBSD auto-install

[FreeBSD ]modify README file to add note about freeBSD auto-install

---

windows/vhba_hot_add_remove/hot_extend_disk_test.yml

change the condition for the nvme 1.3 hot extend known issue

[Windows] nvme hot extend issue fixed in ESXi 8.0U1

---

autoinstall/Ubuntu/Desktop/Subiquity/user-data.j2
autoinstall/Ubuntu/Server/user-data.j2
common/vm_wait_log_msg.yml
linux/deploy_vm/create_unattend_install_iso.yml
linux/deploy_vm/ubuntu/ubuntu_install_os.yml
linux/utils/add_official_online_repo.yml
linux/utils/get_network_config_file.yml
linux/utils/set_network_adapter_status.yml

Install openssh-server with `ssh` key and install missing packages with `packages` key.
Tested with Ubuntu 23.10 Desktop:
```
+--------------------------------------------------------------------------------------+
| Name                      | test_vm_1695696313847                                    |
+--------------------------------------------------------------------------------------+
| Guest OS Distribution     | Ubuntu 23.10 x86_64                                      |
+--------------------------------------------------------------------------------------+
| GUI Installed             | True                                                     |
+--------------------------------------------------------------------------------------+
| CloudInit Version         | …
```

[Ubuntu 23.10] Fix package installation failure at deploy_vm

---

README.md
changelogs/changelog.yml
docker_file/Dockerfile
requirements.txt

Update README, Dockerfile, changelog, and requirements.txt for v3.0 release.

Update documentations for v3.0

---

vars/test.yml

Update vmtools_url_path with VMTools 12.3.5 ISO URL

Update vmtools_url_path with VMTools 12.3.5 ISO URL

---

vars/test.yml

Update vmtools_url_path with VMTools 12.4.0 ISO URL.

Update vmtools_url_path with VMTools 12.4.0 ISO URL

---

vars/test.yml

Update vmtools_url_path with VMTools 12.4.5 ISO URL

Update vmtools_url_path with VMTools 12.4.5 ISO URL

---

vars/test.yml

Update vmtools_url_path with VMTools 12.5.0 ISO URL

Update vmtools_url_path with VMTools 12.5.0 ISO URL

---

linux/utils/add_official_online_repo.yml

Internal test passed for CentOS Stream 10 with online repo.

Update online repo for centos-stream-10

---

common/vm_get_vmtools_status.yml
common/vm_wait_vmtools_status.yml

`vm_tools_install_status` was removed from vmtools_info. This fix is to update `vmtools_is_installed` with `vmtools_info.vm_tools_version_status`

Set vmtools_is_installed with vm_tools_version_status

---

windows/gosv_testcase_list.yml
windows/power_operation_scripts/power_operation_scripts.yml
windows/power_operation_scripts/set_power_script.yml
windows/power_operation_scripts/set_power_script_custom.yml
windows/power_operation_scripts/set_power_script_default.yml
windows/utils/win_check_create_vmtools_conf.yml
windows/utils/win_enable_vmtools_log.yml
windows/utils/win_enable_vss_log.yml

[Windows] Add new test case 'power_operation_scripts'

---

common/create_directory.yml

Added two options for creating local directory: dir_owner and dir_group. So that we can change the owner and group of the new created directory

Add owner and group for creating local directory

---

linux/guest_customization/check_network_config.yml

SLES 16 is using NetworkManager to manage network connections. This change is to get the connection file by nmcli command on SLES 16.

[Linux] Update GOSC network config file for SLES 16

---

windows/deploy_vm/deploy_vm_from_ova.yml

Update vm_ova_path for windows per vars/test.yml if ova_nfs_server_path is defined.
Testing done in case ova_nfs_server_path is undefined.
```
Test Results (Total: 1, Passed: 1, Elapsed Time: 00:08:37)
+-----------------------------------------+
| ID | Name          | Status | Exec Time |
+-----------------------------------------+
|  1 | deploy_vm_ovf | Passed | 00:07:58  |
+-----------------------------------------+
```

Update vm_ova_path for windows

---

README.md
autoinstall/README.md
autoinstall/SLE/16.0/SLES/autoinst.jsonnet
autoinstall/openSUSE/16.0/autoinst.jsonnet
linux/deploy_vm/collect_vm_logs.yml
linux/deploy_vm/create_unattend_install_iso.yml
linux/deploy_vm/deploy_vm_from_iso.yml
linux/deploy_vm/wait_autoinstall_complete.yml
linux/open_vm_tools/install_ovt_from_package.yml
linux/open_vm_tools/install_ovt_from_source.yml
linux/open_vm_tools/ovt_verify_src_install.yml
linux/setup/reconfig_existing_guest.yml
linux/utils/get_linux_system_info.yml

Added unattended install config file for SLES 16.0 and openSUSE Leap 16.0 based on SLES 16.0 Beta3 release.

[Linux] Support SLES 16.0 and openSUSE Leap 16.0 autoinstall

---

linux/guest_customization/check_gosc_support_status.yml
linux/guest_customization/gosc_support_matrix.yml

Jira task: GOSV-4624
The testing is on-going ...
Please help me review it. Thanks.

Fix GOSC support matrix for Pardus 23.x Server 2 of 23

---

linux/setup/test_setup.yml
linux/utils/get_guest_ovt_version_build.yml

VMware Tools  version and build format is changed. This fix is to align this change.

[Linux] Update VMware Tools version and build number

---

windows/wsl_distro_install_uninstall/check_wsl_distro.yml
windows/wsl_distro_install_uninstall/install_wsl.yml
windows/wsl_distro_install_uninstall/install_wsl_distro.yml
windows/wsl_distro_install_uninstall/run_wsl_distro.yml
windows/wsl_distro_install_uninstall/wsl_test_prepare.yml

After installing the WSL, will check if the distributions is also installed together. If not, will install the distribution.

[Windows] Install the WSL distribution if it's not installed along with WSL installation

---

windows/windows_update_install/install_online_updates.yml

Add the parameter to ignore the failure of getting the log file of windows online updates.

[Windows] Ignore the failure of getting the log file of windows online updates

---

common/vm_check_exist.yml
linux/guest_customization/linux_gosc_workflow.yml

```
+------------------------------------------------------------------------------+
| VMTools Version           | 13.0.0 (build-24696409)                          |
+------------------------------------------------------------------------------+
| Config Guest Id           | vmwarePhoton64Guest                              |
+------------------------------------------------------------------------------+
| GuestInfo Guest Id        | vmwarePhoton64Guest                              |
+------------------------------------------------------------------------------+
| GuestInfo Guest Full Name | VMware Photon OS (64-bit)                        |
+------------------------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest …
```

[Linux] Fix package error while installing package open-vm-tools-gosc on Photon OS for perl GOSC

---

linux/deploy_vm/wait_autoinstall_complete.yml

fix autoinstall issue for SLES 16.0 GMC
task:
GOSV-5314

[SLES 16] fix autoinstall issue for SLES 16.0 GMC

---

autoinstall/SLE/16.0/SLES/autoinst.jsonnet

Add SELinux Support when automatic install SLES 16.0

Add SELinux Support when automatic install SLES 16.0
