windows/deploy_vm/deploy_vm.yml
In some slow environment, the Windows OS installation process takes longer than 600s to get the IP address, so here modify this value to 1800s to fit some specific environment or situations.
=> [Bug][Windows] Modify the timeout value for Windows installation

linux/utils/install_uninstall_package.yml
The correct utils task file should be add_official_online_repo.yml.
```
| VM Name             | qiz-214-photon-3.0-bug-verify |
| VM IP               | 10.117.16.102                 |
| Guest OS Type       | VMware Photon OS 3.0 x86_64   |
| VM Tools            | 11.2.5.26209 (build-17337674) |
| Cloud-Init          | 19.4                          |
| Guest ID            | vmwarePhoton64Guest           | …
```
=> Fix the incorrect tasks file path

windows/wintools_complete_install_verify/enable_test_signing.yml, windows/wintools_complete_install_verify/wintools_complete_install_verify.yml
Fixes #8 
When testing on the under development VMware tools, which may contain the un-WHQL signed driver, enable test signing in Windows guest OS before install this VMware tools.
=> [New feature][Windows] Add enable test signing task for Windows VMware tools install

linux/deploy_vm/ubuntu/reconfigure_ubuntu_iso_vm.yml, linux/deploy_vm/ubuntu/ubuntu_install_method.j2, linux/deploy_vm/ubuntu/vars_ubuntu_install.yml
add autoinstall for ubuntu 21.04
test items:
1) check autoinstall for ubuntu 20.10 live server and ubuntu 21.04 live server
2) check the default auto install
test result:
1) set cloud-init as autoinstall method for ubuntu 21.04:
2) set default autoinstall method for ubuntu 21.04:
=> add autoinstall for ubuntu 21.04

common/add_host_in_memory_inventory.yml, common/transfer_file_remote.yml, env_setup/env_setup.yml, linux/deploy_vm/amazonlinux/reconfigure_amazonlinux_vm.yml, linux/deploy_vm/create_unattend_install_iso.yml, linux/deploy_vm/download_iso_and_transfer.yml, windows/deploy_vm/create_unattend_install_iso.yml, windows/wintools_complete_install_verify/download_vmtools_and_transfer.yml
Fixes: #10
When transfer file to ESXi host, we set "ANSIBLE_REMOTE_TMP" environment variable to "/vmfs/volumes/{{ datastore }}" in common task: transfer_file_remote.yml
=> Set ansible_remote_tmp using environment variable when transfer files to ESXi host

linux/check_os_fullname/amazonlinux_fullname_map.yml, linux/check_os_fullname/centos_fullname_map.yml, linux/check_os_fullname/check_os_fullname.yml, linux/check_os_fullname/debian_fullname_map.yml, linux/check_os_fullname/oraclelinux_fullname_map.yml, linux/check_os_fullname/photon_fullname_map.yml, linux/check_os_fullname/rhel_fullname_map.yml, linux/check_os_fullname/sles_fullname_map.yml, linux/check_os_fullname/validate_os_fullname.yml, linux/deploy_vm/amazonlinux/reconfigure_amazonlinux_vm.yml, linux/deploy_vm/deploy_vm_from_ova.yml
On 67GA, flatcar VM's guest full name is like 'Linux 5.10.38-flatcar Flatcar Container Linux by Kinvolk 2765.2.5 Oklo Flatcar Container Linux by Kinvolk 2765.2.5 (Oklo)', and there is no guest os detail info in vm extra config. This fix resolved the issue.
=> Fix flatcar guest name issue

common/vm_rename_snapshot.yml, common/vm_wait_expected_snapshot.yml
Snapshot renaming task takes some time, we need to wait it completed and then assert the task success.
```
+----------------------------------------------+
| Product | Version | Build   | Hostname or IP |
+----------------------------------------------+
| vCenter | 6.7.0   | 8170161 | 10.191.162.225 |
+----------------------------------------------+
| ESXi    | 6.7.0   | 8169922 | 10.191.168.138 |
+----------------------------------------------+
| VM Name             | test_vm                       |
| VM IP               | 10.191.167.228                |
| Guest OS Type       | SLES …
```
=> Wait VM snapshot renaming completed

linux/utils/get_installed_package_info.yml
Fix #51 
The output of querying package information could have spaces following package properties.
For example,
```
"stdout_lines": [
"Name        : openssh-server",
"Version     : 8.0p1",
"Release     : 5.el8",
"Architecture: x86_64",
"Install Date: Mon 07 Jun 2021 08:11:28 AM EDT",
"Group       : System Environment/Daemons",
"Size        : 1034528",
"License     : BSD",
"Signature   : RSA/SHA256, Fri 31 Jul 2020 08:22:03 AM EDT, Key ID 82562ea9ad986da3",
"Source RPM  : openssh-8.0p1-5.el8.src.rpm",
"Build Date  : Fri 31 Jul 2020 08:21:15 AM EDT",
"Build Host  : jenkins-10-147-72-125-6ff307d2-bdc3-47e1-8da0-642273fc4d3d.appad2iad.osdevelopmeniad.oraclevcn.com",
"Relocations : (not relocatable)",
"Vendor      : Oracle America",
"URL         : …
```
=> Update match pattern for filtering package information

linux/deploy_vm/ubuntu/ubuntu_install_os.yml
Fix #54
Ubuntu cloud-init autoinstall will firstly get IP address and then show the autoinstall confirmation message, so add a wait ip task before sending confirmation 'yes'.
```
| Product | Version | Build    | Hostname or IP |
| vCenter | 7.0.2   | 17694817 | 10.161.66.226  |
| ESXi    | 7.0.2   | 17630552 | 10.161.70.69   |
+-------------------------------------------+
| VM Name             | ubuntu-21.04-4      |
+-------------------------------------------+
| VM IP               | 10.161.85.93        | …
```
=> Add wait ip task before continueing ubuntu cloud-init autoinstall

linux/utils/add_repo_from_baseurl.yml
Photon's yum repo file doesn't accept spaces before and after '=', so remove those spaces. The others os distributions which using yum repo accept repo settings with or without spaces before and after '='.
=> Remove spaces in yum repo file

common/vm_set_extra_config.yml, linux/deploy_vm/flatcar/reconfigure_flatcar_vm.yml, linux/utils/device_connectable_enable.yml
Fix #75 
In https://github.com/ansible-collections/community.vmware/commit/f913056612c776b6527aa3c373fe7cb7358d2762#, customvalues was replaced by advanced_settings. Correct the parameter name in common task.
```
Test Results (Total: 1, Failed: 0, No Run: 0, Elapsed Time: 00:06:42):
+----------------------------------+
| Name        | Status | Exec Time |
+----------------------------------+
| device_list | Passed | 00:05:37  |
+----------------------------------+
```
=> VM customvalues was repaced by advanced_settings

docs/KNOWN_ISSUES.md, linux/vhba_hot_add_remove/wait_device_list_changed.yml
Photon OS doesn't support NVMe hot add/remove on existing NVMe controller. So nvme_vhba_device_ops would fail with Photon OS. This fix will not reload NVMe module in Photon OS as it's builtin.
=> Module nvme is builtin in Photon OS. Do not reload it

ansible.cfg, linux/deploy_vm/flatcar/flatcar_post_config.yml, linux/deploy_vm/flatcar/ignition_config.j2, linux/utils/check_service_status.yml, linux/utils/enable_disable_cloudinit_cfg.yml, linux/utils/service_operation.yml, linux/vhba_hot_add_remove/wait_device_list_changed.yml
Fix #79 
```
| VM Name             | test-vm                       |
| VM IP               | 10.193.26.185                 |
| Guest OS Type       | Flatcar 2765.2.5 x86_64       |
| VM Tools            | 11.2.5.26209 (build-17337674) |
| Guest ID            | other3xLinux64Guest           |
| Hardware Version    | vmx-13                        | …
```
=> Run shell command to rescan hard disks on Flatcar

plugin/ansible_vsphere_gosv_log.py
Fix #58 
Tested with an empty test.yml
```
TASK [Set the log files path of this test run] *******************************************************************
task path: /home/qiz/workspace/github/ansible-vsphere-gos-validation/env_setup/create_local_log_path.yml:5
"msg": "The task includes an option with an undefined variable. The error was: 'vm_name' is undefined\n\nThe error appears to be in '/home/qiz/workspace/github/ansible-vsphere-gos-validation/env_setup/create_local_log_path.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Create the current test run log files path in specified dir or in default dir.\n- name: \"Set the …
```
=> Fix #58 Check self.testing_vars before use it

docs/KNOWN_ISSUES.md, linux/utils/add_official_online_repo.yml
Fix #86 
```
| VM Name             | photon-os-3.0                 |
| VM IP               | 10.78.204.46                  |
| Guest OS Type       | VMware Photon OS 3.0 x86_64   |
| VM Tools            | 11.2.5.26209 (build-17337674) |
| Cloud-Init          | 18.3                          |
| Guest ID            | vmwarePhoton64Guest           |
| …
```
=> Change photon repo's baseurl for Photon 3.x and earlier

README.md, common/get_guest_system_info.yml, linux/check_inbox_driver/check_inbox_driver.yml, linux/check_os_fullname/check_os_fullname.yml, linux/check_os_fullname/otherlinux_fullname_map.yml, linux/check_os_fullname/validate_os_fullname.yml, linux/deploy_vm/deploy_vm_from_iso.yml, linux/guest_customization/check_network_config.yml, linux/guest_customization/linux_gosc_start.yml, linux/guest_customization/linux_gosc_workflow.yml, linux/network_device_ops/enable_new_ethernet.yml, linux/open_vm_tools/get_install_uninstall_cmd.yml, linux/open_vm_tools/ovt_verify_install.yml, linux/open_vm_tools/set_ovt_facts.yml, linux/secureboot_enable_disable/secureboot_enable_disable.yml, linux/utils/add_extra_online_repo.yml, linux/utils/add_official_online_repo.yml, linux/utils/add_repo_from_baseurl.yml, linux/utils/check_guest_os_gui.yml, linux/utils/disable_repo.yml, linux/utils/enable_auto_login.yml, linux/utils/install_uninstall_package.yml, linux/utils/set_proxy.yml, linux/utils/test_setup.yml, linux/vgauth_check_service/vgauth_check_service.yml, linux/vhba_hot_add_remove/vhba_device_hot_add_remove.yml, linux/vhba_hot_add_remove/wait_device_list_changed.yml
Add a new running time variable guest_os_family to categorize OS distributions, such as:
```
For RedHat, CentOS, OracleLinux, Rocky, Amazon, Fedora, guest_os_family="RedHat" 
For SLES, SLED, guest_os_family="Suse"
For Ubuntu, Debian, guest_os_family="Debian"
For VMware Photon OS, guest_os_family="VMware Photon OS" 
For Flatcar,  guest_os_family="Flatcar"
For Windows and Windows Server, guest_os_family="Windows"
```
With this variable, we can easily extend the support OS list for OS varieties.
=> Support Rocky Linux

common/vm_revert_snapshot.yml, common/vm_take_snapshot.yml, linux/utils/test_rescue.yml, windows/setup/rescue_cleanup.yml
Fixes #89 
1. Refine common task `vm_revert_snapshot.yml`.
2. Add ignore_errors in common task `vm_take_snapshot.yml`.
3. Set ignore_errors to True in test rescue tasks.
=> Add ignore_errors in vm_take_snapshot.yml

README.md, common/get_guest_system_info.yml, linux/check_os_fullname/check_os_fullname.yml, linux/check_os_fullname/otherlinux_fullname_map.yml, linux/check_os_fullname/validate_os_fullname.yml, linux/deploy_vm/flatcar/flatcar_post_config.yml, linux/deploy_vm/flatcar/install_python3.sh, linux/deploy_vm/flatcar/reconfigure_flatcar_vm.yml, linux/vhba_hot_add_remove/vhba_device_hot_add_remove.yml
Fix #100, #102, #91
Changes include:
1. Map OS family to RedHat if ansible_distribution_file_variety="RedHat"
2. Validate other Linux's guest full name with linux/check_os_fullname/otherlinux_fullname_map.yml according to linux kernel version. And if OS detailed data is detected in guest full name, pass the test.
3. Exclude OracleLinux from skipping tests lsilogic_vhba_device_ops and lsilogicsas_vhba_device_ops, as OracleLinux still supports the two scsi controllers.
4. Skip nvme_vhba_device_ops if VM's hardware version is less than 13.
5. Set /etc/environment in Flatcar to include the binary dir path to python, so that it can be discovered automatically by ansible.
=> Add Alma Linux support

linux/deploy_vm/set_new_vm_user_account.yml, linux/guest_customization/linux_gosc_workflow.yml, linux/network_device_ops/network_device_test.yml, linux/setup/reconfig_existing_guest.yml, linux/utils/cloudinit_pkg_check.yml, linux/utils/install_uninstall_package.yml, linux/vhba_hot_add_remove/wait_device_list_changed.yml, vars/test.yml
Fix #97 Only update photon cache before taking base snapshot, then the following installing packages won't need to update again.
Fix #128 Add a default regular user 'vmware' if vm_username is root.
=> Fix 97 update photon cache

README.md, linux/check_inbox_driver/check_inbox_driver.yml, linux/guest_customization/linux_gosc_workflow.yml, linux/network_device_ops/enable_new_ethernet.yml, linux/open_vm_tools/get_install_uninstall_cmd.yml, linux/open_vm_tools/ovt_verify_status.yml, linux/open_vm_tools/set_ovt_facts.yml, linux/secureboot_enable_disable/secureboot_enable_disable.yml, linux/utils/check_guest_os_gui.yml, linux/utils/enable_auto_login_fly_dm.yml, linux/utils/install_uninstall_package.yml, linux/vgauth_check_service/vgauth_check_service.yml, linux/vhba_hot_add_remove/wait_device_list_changed.yml
Hello.
This is an adaptation of tests for the Astra Linux Orel distro (https://astralinux.ru/).
Image for tests - https://nas01.astralinux.ru/sharing/wJss3PxqA
```
+-------------------------------------------------------------+
| Product | Version | Build    | Hostname or IP               |
+-------------------------------------------------------------+
| vCenter | 7.0.2   | 17694817 | vcsa01.stand01.astralinux.ru |
+-------------------------------------------------------------+
| ESXi    | 7.0.2   | 17867351 | esxi.astratest.local         |
+-------------------------------------------------------------+
+------------------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                                 | …
```
=> Add Astra Linux support

linux/check_os_fullname/rhel_fullname_map.yml
```
| Product | Version | Build    | Hostname or IP |
| vCenter | 7.0.0   | 15952599 | x.x.x.x   |
| ESXi    | 7.0.0   | 15843807 | x.x.x.x  |
+-----------------------------------------------------------------------------------+
| Name                      | test_vm_1639020563600                                 |
+-----------------------------------------------------------------------------------+
| IP                        | x.x.x.x                                        |
+---------------------------------------------------------------------------------- …
```
=> Fix #185 correct guest full name of rhel 9 on ESXi < 7.0.0

common/README.md, common/vm_get_vbs_status.yml, windows/cpu_hot_add_basic/cpu_hot_add_basic.yml, windows/memory_hot_add_basic/memory_hot_add_basic.yml, windows/wintools_complete_install_verify/enable_test_signing.yml, windows/wintools_complete_install_verify/get_vbs_enable_status.yml, windows/wintools_complete_install_verify/wintools_complete_install_verify.yml
Fixes #164
Fixes #144 
1. disable secure boot before enable test signing,
2. if VBS is enabled, then test will be skipped on development tools.
=> [Windows] Add secureboot check before enable testsigning

README.md, common/README.md, common/vm_remove_serial_port.yml, linux/deploy_vm/deploy_vm_from_iso.yml, linux/deploy_vm/templates/ubuntu-iso-user-data.j2, linux/deploy_vm/templates/ubuntu-ova-user-data.j2, linux/deploy_vm/ubuntu/ubuntu_install_os.yml, linux/deploy_vm/ubuntu/vars_ubuntu_install.yml, linux/guest_customization/check_gosc_support_status.yml, linux/guest_customization/check_network_config.yml, linux/guest_customization/linux_gosc_start.yml, linux/guest_customization/linux_gosc_workflow.yml, linux/guest_customization/wait_gosc_complete_msg.yml, linux/utils/enable_disable_cloudinit_cfg.yml
In Ubuntu 21.10, the network interface name is changed, not ens192 any more. So remove the network interface config from cloud-init user-data for autoinstall, and remove the serial port after OS installation to fix #176
=> Fix ubuntu issue #175 and #176

common/skip_test_case.yml, linux/check_os_fullname/otherlinux_fullname_map.yml, linux/check_os_fullname/validate_os_fullname.yml, windows/deploy_vm/deploy_vm.yml
Use end_host instead of end_play to skip the rest of tasks in a playbook.
=> Fix #211 Replace end_play with end_host

linux/utils/ethernet_ip_get.yml
Fix #198 
```
+---------------------------------------------------------------------------------------------+
| Guest OS Type             | Flatcar 3033.2.0 x86_64                                         |
+---------------------------------------------------------------------------------------------+
| VMTools Version           | 11.3.5.31214 (build-18557794)                                   |
+---------------------------------------------------------------------------------------------+
| CloudInit Version         |                                                                 |
+---------------------------------------------------------------------------------------------+
| Config Guest Id           | other3xLinux64Guest …
```
=> Fix #198 Flatcar 3033.2.0 check_ip_address

common/vm_wait_log_msg.yml, windows/check_os_fullname/check_os_fullname.yml
When there is new or unknown guest ID got from VM, no get mapping expected guest fullname, set it to the OS fullname got in guest OS.
=> [Windows] Set expected guest fullname to OS fullname got from guest

common/vm_add_serial_port.yml, common/vm_remove_serial_port.yml, linux/deploy_vm/deploy_vm_from_iso.yml, linux/guest_customization/check_dns.yml, linux/guest_customization/check_etc_hosts.yml, linux/guest_customization/check_hostname_and_domain.yml, linux/guest_customization/check_network_config.yml, linux/guest_customization/check_timezone_and_hwclock.yml, linux/guest_customization/linux_gosc_start.yml, linux/guest_customization/linux_gosc_verify.yml
Ignore below GOSC known issues:
1. Fix #201: gosc_cloudinit_staticip failed due to not default gateway from VC 6.5 U2 and eariler, 6.7GA and U1. This issue has been fixed in VC 6.5U3, 6.7U2, and later releases. See https://docs.vmware.com/en/VMware-vSphere/6.5/rn/vsphere-vcenter-server-65u3-release-notes.html#guest-os-issues-resolved and https://docs.vmware.com/en/VMware-vSphere/6.7/rn/vsphere-vcenter-server-67u2-release-notes.html#guest-os-issues-resolved. 
2. Fix #206: gosc_cloudinit_dhcp failed due to DNS settings customization failures due to Ubuntu issue: https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1776452.
3. From VC 6.5 U3 and earlier builds, GOSC won't sent completed state keyword to vmware.log. 
=> Fix #206 and #201 Warn about GOSC DNS failures on Ubuntu and default gateway failures

linux/guest_customization/check_gosc_support_status.yml, linux/guest_customization/linux_gosc_workflow.yml
Fix #172 Perl GOSC on Photon OS requires OS bundled open-vm-tools. If the OVT installed is not from Photon OS's repository, skip to run perl GOSC testing on it.
```
+---------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                |
|                           | bitness='64'                      |
|                           | distroName='VMware Photon OS'     |
|                           | distroVersion='4.0'               |
|                           | familyName='Linux'                |
|                           | kernelVersion='5.10.61-1.ph4-esx' |
|                           | prettyName='VMware Photon OS 4.0' |
+---------------------------------------------------------------+
Test Results (Total: 4, Failed: 0, No …
```
=> Skip Perl GOSC when Photon doesn't install bundled open-vm-tools

linux/memory_hot_add_basic/memory_set_and_validate.yml
Fix #235 by updating inventory after memory cold add
```
+-----------------------------------------------------------+
| Guest OS Type             | VMware Photon OS 4.0 x86_64   |
+-----------------------------------------------------------+
| VMTools Version           | 11.3.5.31214 (build-18557794) |
+-----------------------------------------------------------+
| CloudInit Version         |                               |
+-----------------------------------------------------------+
| Config Guest Id           | vmwarePhoton64Guest           |
+-----------------------------------------------------------+
| Hardware Version          | vmx-14                        |
+-----------------------------------------------------------+
| GuestInfo Guest Id        | vmwarePhoton64Guest …
```
=> Fix memory_hot_add_basic failure due to ip change

env_setup/env_setup.yml, linux/open_vm_tools/install_ovt.yml, linux/utils/add_official_online_repo.yml, vars/test.yml
Fix #237 CentOS 8.x and earlier repos were moved out of CentOS mirrors
https://vault.centos.org provides access to older archived versions, including CentOS 8.x and earlier versions.
http://mirror.stream.centos.org contains new CentOS Stream releases, starting from release '9-stream'.
=> Fix #237 Update baseurl for CentOS online repos

env_setup/create_local_log_path.yml, env_setup/env_cleanup.yml
We are not using error_msg_path and test_result_file in tests any more, so remove them.
```
PLAY [env_cleanup] *************************************************************
Read vars_file '{{ testing_vars_file | default('../vars/test.yml') }}'
META: ran handlers
Read vars_file '{{ testing_vars_file | default('../vars/test.yml') }}'
TASK [Set cleanup VM to False by default] **************************************
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/env_setup/env_cleanup.yml:11
"cleanup_vm": false
},
}
Read vars_file '{{ testing_vars_file | default('../vars/test.yml') }}'
Read vars_file '{{ testing_vars_file | default('../vars/test.yml') …
```
=> Variables error_msg_path and test_result_file are not needed any more

common/README.md, common/vm_create_with_ide_disk.yml, common/vm_get_id.yml, linux/deploy_vm/deploy_vm_from_iso.yml, sample/test.yml, vars/test.yml, windows/deploy_vm/deploy_vm.yml
This is a workaround for issue https://github.com/vmware/ansible-vsphere-gos-validation/issues/224, so that it won't block our IDE testing. After https://github.com/vmware/ansible-vsphere-gos-validation/issues/224 is fixed, we can remove the workaround task.
=> Add workaround task for creating VM with IDE boot disk

linux/guest_customization/check_gosc_support_status.yml, linux/guest_customization/gosc_support_matrix.yml, plugin/ansible_vsphere_gosv_log.py
Fix #205 add gosc support matrix for SLES, AlmaLinux, Rocky, Debian and Ubuntu.
=> Add gosc support matrix

linux/deploy_vm/ubuntu/reconfigure_ubuntu_ova_vm.yml
Fix #248 
```
+-----------------------------------------------------------+
| Guest OS Type             | Ubuntu 21.10 x86_64           |
+-----------------------------------------------------------+
| Hardware Version          | vmx-14                        |
+-----------------------------------------------------------+
| VMTools Version           | 11.3.0.29534 (build-18090558) |
+-----------------------------------------------------------+
| CloudInit Version         | 21.3-1-g6803368d-0ubuntu3     |
+-----------------------------------------------------------+
| Config Guest Id           | ubuntu64Guest                 |
+-----------------------------------------------------------+
| GuestInfo Guest Id        | ubuntu64Guest                 | …
```
=> Remove serial port from Ubuntu VM after OVA deployment

linux/deploy_vm/ubuntu/prepare_ubuntu_iso_install.yml
If the Ubuntu ISO name doesn't contain any version information, like jammy-live-server-amd64.iso, set fact of ubuntu_install_method would fail as ubuntu_version is empty. And the task would fail with below message:
```
2022-03-03 03:53:27,003 | TASK [Set Ubuntu autoinstall method] ***********************
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_20.04.4_ISO/ansible-vsphere-gos-validation/linux/deploy_vm/ubuntu/prepare_ubuntu_iso_install.yml:21
"msg": "Input version value cannot be empty"
}
```
=> Fix ubuntu_version failure when ISO name has no version

autoinstall/Debian/10/preseed.cfg, linux/guest_customization/linux_gosc_workflow.yml, linux/utils/install_uninstall_package.yml
1. Fix #279 by installing sg3-utils at deployment for new VM, and update cache while installing it on existing VM.
2. Skip cloud-init GOSC testing when cloud-init version is not 22.1 or later.
```
+-------------------------------------------------------------------------+
| Guest OS Distribution     | Debian 11.3 x86_64                          |
+-------------------------------------------------------------------------+
| CloudInit Version         | 20.4.1-2+deb11u1                            |
+-------------------------------------------------------------------------+
| GUI Installed             | True                                        |
+-------------------------------------------------------------------------+
| Config Guest Id           | debian11_64Guest …
```
=> Fix Debian 11.3 testing issue

linux/setup/reconfig_existing_guest.yml
Fix #287 
Issue described in #287 was reproduced. After OS installation, the PackageKit service doesn't appear in system service list. So it is still required to check PackageKit package exists or not, and then uninstall it
=> Remove PackageKit from SLED no matter packagekit.service exists or not

linux/check_inbox_driver/check_inbox_driver.yml
Fix #163 Check the inbox driver's version of vmw_pvrdma and ptp_vmw:
If the driver has version information, get the driver's versioin;
otherwise, if the driver has srcversion information, get the driver's srcversion;
otherwise, if the driver has vermagic information, get the driver's vermagic;
otherwise, if the driver exists but has no information about version/srcversion/vermagic, leave its version empty.
otherwise, set the driver's version as 'N/A' which indicates the driver is not found.
Example of inbox driver versions:
CentOS 8.5
```
"inbox_drivers_versions": {
"Release": "CentOS 8.5",
"cloud-init": "21.1",
"kernel": "4.18.0-348.el8.x86_64",
"open-vm-tools": "11.2.5.26209 (build-17337674)",
"ptp_vmw": "188B9501F71B9AD0C3834B4",
"vmw_balloon": "1.5.0.0-k",
"vmw_pvrdma": …
```
=> Fix #163 Check inbox driver vmw_pvrdma and ptp_vmw 

README.md, requirements.txt
`xorriso` is not a python package but linux tool, so remove it from requirements.txt
=> Remove xorriso from requirement.txt and add to README

plugin/ansible_vsphere_gosv_log.py
Fix #161: With this fix, failed loop task items would not be written into failed_tasks.log
=> Remove ignored failed tasks from failed_tasks.log

linux/deploy_vm/ubuntu/reconfigure_ubuntu_ova_vm.yml, linux/vhba_hot_add_remove/hot_add_remove_disk.yml, linux/vhba_hot_add_remove/wait_device_list_changed.yml
Fix #199 
In Flatcar 3033.2.0 and later versions, deleted LSILogic disk still can be shown in output of `lsblk`. 
In Ubuntu 22.04, rescan-scsi-bus.sh would remove all SCSI block devices, not only the removed LSILogic disk.
This workaround would check the deleted disk size and then mark it as deleted.
```
+-------------------------------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                                                  |
|                           | bitness='64'                                                        |
|                           | buildNumber='2022-05-27-1432'                                       |
|                           | distroName='Flatcar Container Linux by Kinvolk' …
```
=> Workaround for rescan deleted LSILogic disk in Flatcar and Ubuntu 22.04

common/README.md, common/vm_answer_question.yml, common/vm_set_power_state.yml
```
TASK [Set VM power state to 'powered-on'] *******************************************************************************
task path: ansible-vsphere-gos-validation/common/vm_set_power_state.yml:34
"answer": null,
"changed": true,
"instance": {
"advanced_settings": {
...
},
"annotation": "",
"current_snapshot": null,
"customvalues": {},
"guest_consolidation_needed": false,
"guest_question": {
"_vimtype": "vim.vm.QuestionInfo",
"choice": {
"_vimtype": "vim.option.ChoiceOption",
"choiceInfo": [
{
"_vimtype": "vim.ElementDescription",
"key": "0",
"label": "button.serial.file.append",
"summary": "Append"
},
{
"_vimtype": "vim.ElementDescription",
"key": "1",
"label": "button.serial.file.overwrite",
"summary": …
```
=> Answer question about serial port output file existence at VM powerr-on

linux/guest_customization/check_dns.yml
The systemd-resolve output is stored in /tmp/systemd_resolve_status.txt on the guest machine but at next step playbook tries to download /tmp/systemd_resolve_status (without extension) to controller host. This issue makes impossible to pass GOS tests on Ubuntu hosts.
=> Fix: lost file extension

autoinstall/Photon/ks.cfg, linux/deploy_vm/deploy_vm_from_iso.yml, linux/deploy_vm/deploy_vm_from_ova.yml, linux/deploy_vm/templates/photon-user-data.j2, linux/guest_customization/check_gosc_log.yml, linux/setup/reconfig_existing_guest.yml, linux/utils/collect_cloudinit_logs.yml, linux/utils/install_uninstall_package.yml, linux/utils/repo_update.yml, linux/utils/service_operation.yml, linux/utils/set_dns.yml
This PR fixed below issues:
1. Failed to set root password with cloud-init at deploying Photon 3 OVA image. The issue has been fixed in Photon 3 shadow-4.6-6, but this fix worked around it for Photon 3 OVA images using shadow-4.6-5 or earlier. Meanwhile, added tasks for collecting cloud-init logs after deploying Photon and Ubuntu OVA for cloud-init problems triage.
2. Installing packages in Photon 3 might fail with error like "Couldn't resolve host name" or "Couldn't connect server" at the first time of executing `tdnf install`. Ultimately the root cause of the issue was this.
https://github.com/vmware/photon/commit/5b4f598f0ef30984217229c8bada56ff806e96eb
And fix is https://github.com/vmware/photon/commit/838af600bcb81a04de31af6b692e8e37c146d0ab …
=> Fix Photon 3 OVA deploy failure and package installation failures

common/ovf_deploy.yml
Add vm_folder in common task ovf_deploy.yml to specify which vm folder will the new OVF template be deployed.
=> Add vm_folder for deploying OVF templates

plugin/ansible_vsphere_gosv_log.py
Fix #182 
Example output
```
2022-08-04 11:27:41,004 | TASK [main][Gathering Facts] *******************************
task path: /home/qiz/workspace/github/ansible-vsphere-gos-validation/main.yml:5
ok: [localhost] => { 
"ansible_all_ipv4_addresses": [
"10.117.16.35",
"172.18.0.1",
"172.17.0.1"
],  
```
=> Print playbook name before task name

docs/KNOWN_ISSUES.md, linux/guest_customization/linux_gosc_verify.yml, linux/vhba_hot_add_remove/wait_device_list_changed.yml, plugin/ansible_vsphere_gosv_log.py, windows/check_os_fullname/check_os_fullname.yml, windows/check_quiesce_snapshot/check_vmx_disk_enable_uuid.yml, windows/vhba_hot_add_remove/hotadd_vm_disk_existing_ctrl.yml, windows/vhba_hot_add_remove/hotremove_vm_disk_ctrl.yml
Add tag `known_issue` to debug message which describes a known issue, and collect them in log plugin.
Example `known_issues.log`:
```
2022-08-08 10:02:54,008 | Known Issue in Play [check_os_fullname] ********************
2022-08-08 10:02:54,008 | TASK [check_os_fullname][Known issue - ignore incorrect guestID of Windows 11] 
task path: /home/worker/workspace/Ansible_Regression_Windows_11_64/ansible-vsphere-gos-validation/windows/check_os_fullname/check_os_fullname.yml:37
"msg": [
"The guestID of Windows 11 guest in guestinfo is empty on ESXi 7.0U3c. Ignore this known issue.",
"Please refer to https://kb.vmware.com/s/article/86517."
]
}
2022-08-08 10:05:05,008 | Known Issue in Play [nvme_vhba_device_ops] *****************
2022-08-08 10:05:05,008 | TASK …
```
=> Tag known issues and collect them into known_issues.log

linux/check_inbox_driver/check_inbox_driver.yml, linux/check_inbox_driver/get_inbox_drivers.yml, linux/check_inbox_driver/get_os_release.yml, linux/check_inbox_driver/get_xorg_version.yml
Tested with Oracle Linux 9.0 and failed as expected:
```
[
{
"Release": "OracleLinux 9.0",
"cloud-init": "21.1",
"kernel": "5.15.0-0.30.19.el9uek.x86_64",
"open-vm-tools": "11.3.5.31214 (build-18557794)",
"vmw_balloon": "ECD69D409A352515CC15B45",
"vmw_pvrdma": "F0092285123462CEC485ECB",
"vmw_pvscsi": "1.0.7.0-k",
"vmw_vmci": "1.1.6.0-k",
"vmw_vsock_virtio_transport_common": "1EEE6DF92F445D52FF1FB8F",
"vmw_vsock_vmci_transport": "1.0.5.0-k",
"vmwgfx": "2.19.0.0",
"vmxnet3": "1.6.0.0-k",
"vsock": "1.0.2.0-k",
"xf86-video-vmware": "13.2.1",
"xorg server": "1.20.11"
}
]
```
Known issue:
```
TASK [Print inbox drivers' filenames] ******************************************
task path: /home/worker/workspace/Ansible_Regression_OracleLinux_9.x/ansible-vsphere …
```
=> Add inbox drivers's filename checking in check_inbox_driver

linux/check_os_fullname/check_os_fullname.yml, linux/check_os_fullname/rocky_fullname_map.yml, linux/check_os_fullname/validate_os_fullname.yml
Rocky Linux built-in open-vm-tools 11.3.5-1.el8 or 11.3.5-1.el9 can't well recognize the guest full name as Other 4.x Linux (64-bit) or Other 5.x Linux (64-bit). They modified open-vm-tools source code which leads unexpected behavior at recognizing guest full name. The guest full name is always same as guest OS version selection in VM's settings.
It requires Rocky Linux fix it in their own open-vm-tools 11.3.5
In this fix, the test case will fail if the guest full name is not Other N.x Linux (64-bit) when Rocky Linux has built-in OVT 11.3.5, but a known_issue is been tagged, so that user can identify it easily.
```
2022-08-18 08:34:40,018 | Known Issue in Play [check_os_fullname] ********************
2022-08-18 08:34:40,018 | TASK …
```
=> Update Rocky Linux guest OS fullname mapping

linux/check_inbox_driver/get_inbox_drivers.yml
Check_inbox_driver should still fail until it's been fixed, so that we can keep tracking it. With the known_issues.log, users can identify it is a known issue, not a new issue.
```
2022-08-19 04:13:20,019 | Failed at Play [check_inbox_driver] ************************
2022-08-19 04:13:20,019 | TASK [check_inbox_driver][Check inbox driver's filename is valid] 
task path: /home/worker/workspace/Ansible_Regression_OracleLinux_9.x/ansible-vsphere-gos-validation/linux/check_inbox_driver/get_inbox_drivers.yml:141
failed: [localhost] => (item={'key': 'vsock', 'value': '(builtin)'}) => {
"ansible_loop_var": "item",
"assertion": "(item.value | basename) is match('.*\\.ko')",
"item": {
"key": "vsock",
"value": …
```
=> Fail check_inbox_driver for Oracle Linux 9.0 with UEK R7 with known issue

autoinstall/Ubuntu/Server/user-data.j2, linux/deploy_vm/rebuild_unattend_install_iso.yml, linux/network_device_ops/enable_new_ethernet.yml
This fix resolved below two issues:
1. Add "autoinstall" to BIOS boot config file isolinux/txt.cfg for fully auto install with Ubuntu 20.04.x live server image.
2. Remove net-tools from Ubuntu autoinstall config file because its installation failed in Ubuntu 20.04.5.
=> Fix ubuntu 20.04.5 autoinstall failure

common/vm_wait_expected_snapshot.yml, linux/utils/ssh_keep_alive.yml, linux/vhba_hot_add_remove/wait_device_list_changed.yml
Ubuntu 22.10 changed sshd service name to ssh.service not sshd.service any more. This fix checked sshd.service existence firstly. If it doesn't exist, check ssh.service, and then use the existing one  to restart sshd service.
Besides, lsilogic_vhba_device_ops still fails with Ubuntu 22.10, so change the SCSI rescan method for both 22.04 and 22.10.
=> Fix Ubuntu sshd service name for setting TCPKeepAlive

linux/secureboot_enable_disable/check_secureboot_support_status.yml, linux/secureboot_enable_disable/secureboot_enable_disable.yml
Skip secureboot testing for OS listed in https://kb.vmware.com/s/article/88737 when VM's hardware version >= 20.
We can't skip deploy_vm for these Linux guests as it requires ansible distribution information.
=> [Linux] Skip testing secureboot enable or disable for OS with vulnerable bootloader

autoinstall/RHEL/8/server_without_GUI/ks.cfg, linux/check_inbox_driver/get_inbox_drivers.yml, linux/deploy_vm/deploy_vm_from_iso.yml, linux/utils/add_official_online_repo.yml, plugin/ansible_vsphere_gosv_log.py
Oracle Linux 9.0 GA release doesn't have vsock and vmw_vsock_vmci_transport modules, see https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=17884. The issue has been fixed in latest UEK R7 kernel V5.15.0-2.52.3. OS lead requested to upgrade UEK R7 after autoinstall so that latest UEK R7 can be tested. 
Meanwhile, 
1. Removed 'syspurpose' command from ks.cfg as OracleLinux 9.0 doesn't support.
2. Increased the delay and reduced the retries for searching autoinstall complete message.
3. Fixed plugin exception
=> [Linux] Upgrade OracleLinux 9.0 to latest UEK kernel

common/skip_test_case.yml, linux/deploy_vm/deploy_vm.yml, linux/open_vm_tools/ovt_verify_install.yml, vars/test.yml, windows/deploy_vm/deploy_vm.yml, windows/wintools_complete_install_verify/wintools_complete_install_verify.yml
When new_vm=false, deploy_vm will be skipped, so changing its test result to 'Skipped' is more proper.
When update_vmtools=false, ovt_verify_install/wintools_complete_install_verify will be skipped, so changing its test result to 'Skipped' is more proper.
=> Replace test result 'No Run' with 'Skipped' for test cases to be skipped

autoinstall/Fedora/36/Server/ks.cfg, autoinstall/Fedora/36/ks.cfg, autoinstall/README.md, linux/check_os_fullname/check_os_fullname.yml, linux/cpu_hot_add_basic/cpu_hot_add_basic.yml, linux/deploy_vm/deploy_vm_from_iso.yml, linux/guest_customization/check_gosc_support_status.yml, linux/vhba_hot_add_remove/wait_device_list_changed.yml
Added kickstart file for Fedora autoinstall, and fixed test case failures.
Tested with Fedora Server 36 and passed:
```
+-----------------------------------------------------------------------+
| Name                      | test_fedora_36_server                     |
+-----------------------------------------------------------------------+
| Guest OS Distribution     | Fedora 36 x86_64                          |
+-----------------------------------------------------------------------+
| Hardware Version          | vmx-20                                    |
+-----------------------------------------------------------------------+
| VMTools Version           | 12.1.0 (build-20219665)                   |
+----------------------------------------------------------------------- …
```
=> [New Feature][Fedora] Support Fedora autoinstall

autoinstall/UOS/Server/20/1050a/ks.cfg, linux/deploy_vm/deploy_vm_from_iso.yml
Environment name graphical-server-environment-dde can not be recognized in UOS Server 20 1050u1a, so replace it with "Server with DDE". And send ENTER key at boot screen to enter installation.
=> Fix software selection for UOS Server 20 1050u1a

README.md
1. Changed header  `Supported Guest OS` to `Compatible Guest Operating Systems`.
2. Added `Fedora Server 36 and later` to `Compatible Guest Operating Systems`.
3. Replaced `OS` with `operating system`.
=> Add Fedora server to Compatible Guest Operating Systems

linux/guest_customization/gosc_support_matrix.yml
Skip GOSC testing on builds earlier than VC 7.0U3f for Rocky, AlmaLinux, OracleLinux 9.x according to https://kb.vmware.com/s/article/88199. 
=> [Linux] Skip GOSC testing on builds earlier than VC 7.0U3f for Rocky, AlmaLinux, OracleLinux 9.x

linux/check_inbox_driver/check_inbox_driver.yml
Signed-off-by: ZouYuhua <zouy@vmware.com>
**Issue:**
2022-11-15 05:33:47,015 | TASK [check_inbox_driver][Dump inbox drivers versions] *****
task path: /home/worker/workspace/lli_Pardus_21.x_64bit_70U1_PARAVIRTUAL_VMXNET3_EFI/ansible-vsphere-gos-validation/linux/check_inbox_driver/check_inbox_driver.yml:80
"checksum": "dfc38c87136a254159b6d9485a1320423a254401",
"diff": [],
"module_args":
{ "_original_basename": "tmpjjsgzar_", "attributes": null, "backup": false, "checksum": "dfc38c87136a254159b6d9485a1320423a254401", "content": null, "dest": "/home/worker/workspace/lli_Pardus_21.x_64bit_70U1_PARAVIRTUAL_VMXNET3_EFI/ansible-vsphere-gos-validation/logs/Pardus-21.3-XFCE/2022-11-15-05-31-51/check_inbox_driver/pardus-gnu/linux-21 …
=> check_inbox_driver test failed in Pardus 21.3 due to slash in distribution name

autoinstall/Ubuntu/Server/user-data.j2, common/esxi_get_guest_config_options.yml, linux/utils/add_local_dvd_repo.yml
There is no default GPG key for SLES/SLED, so remove GPG check for adding SLES/SLED repos. 
Ubuntu 20.04.5 server failed to ndctl, rdma packages during deploy_vm, so in this changes only Ubuntu Server >= 22.04 will install these packages at deploy_vm. Ubuntu 20.04.5 will install these packages in test cases.
=> Fix regression issue found in SLES/SLED/Ubuntu

windows/secureboot_enable_disable/secureboot_enable_disable.yml
=> skip test case secureboot_enable_disable when VBS is enabled

plugin/ansible_vsphere_gosv_log.py
Tested with Windows:
```
+----------------------------------------------------------------------+
| Name                      | wsl_win_server_25276                     |
+----------------------------------------------------------------------+
| IP                        | x.x.x.x                           |
+----------------------------------------------------------------------+
| Guest OS Distribution     | Microsoft Windows Server 2022 Datacenter |
|                           | 10.0.25276.0 64-bit                      |
+----------------------------------------------------------------------+
| Hardware Version          | vmx-20                                   |
+----------------------------------------------------------------------+
| VMTools Version           | …
```
=> Fix empty CloudInit Version and GUI Installed in results.log

common/vm_configure_cdrom.yml
=> change msg.autoanswer to msg.autoAnswer

linux/network_device_ops/check_pvrdma_support_status.yml
Block PVRDMA testing when there is no vCenter Server defined.
```
2023-02-22 05:09:59,022 | Failed at Play [pvrdma_network_device_ops] *****************
2023-02-22 05:09:59,022 | TASK [pvrdma_network_device_ops][Skip testcase: pvrdma_network_device_ops, reason: Blocked] 
task path: /home/worker/workspace/Ansible_Cycle_CentOS_8.x/ansible-vsphere-gos-validation/common/skip_test_case.yml:21
"msg": "Test case is blocked because test environment doesn't have vCenter Server, which doesn't meet PVRDMA requirements"
}
error message:
Test case is blocked because test environment doesn't have vCenter Server, which doesn't meet PVRDMA requirements
```
=> [Linux] Check vCenter Server is defined before PVRDMA testing

common/vm_wait_guest_ip.yml, linux/network_device_ops/apply_new_network_config.yml, linux/network_device_ops/check_and_reload_pvrdma.yml, linux/network_device_ops/hot_add_network_adapter.yml, linux/network_device_ops/hot_remove_network_adapter.yml, linux/network_device_ops/network_status_validate.yml, linux/network_device_ops/prepare_network_device_test.yml, linux/network_device_ops/pvrdma_network_device_ops.yml, linux/network_device_ops/refresh_pvrdma_client_vm_ip.yml, linux/utils/get_network_config_file.yml
After the instant cloned client VM reset, its IP address may be same with server VM because of the MAC address hasn't change. Usually after a few seconds, the MAC address will be changed to same with VM's settings and then its IP address would also be changed. 
This fix will remove MAC or UUID from network adapter 1's network config file before instant clone, and then refresh client VM's IP address till it has different IP with server VM. After that, the testing can go ahead.
=> Fix the issue that PVRDMA client VM has same IP address with server VM

vars/test.yml
Fix 2466: Update 12.2.0 vmtools_url_path for Win
=> Update 12.2.0 vmtools_url_path and vmtools_iso_path for Windows

linux/guest_customization/linux_gosc_start.yml
Cloud-init GOSC complete message was changed in 23.1 or later.
```
+-----------------------------------------------------------------+
| CloudInit Version         | 23.1.1                              |
+-----------------------------------------------------------------+
| GUI Installed             | False                               |
+-----------------------------------------------------------------+
| Config Guest Id           | vmwarePhoton64Guest                 |
+-----------------------------------------------------------------+
| GuestInfo Guest Id        | vmwarePhoton64Guest                 |
+-----------------------------------------------------------------+
| GuestInfo Guest Full Name | VMware Photon OS (64-bit)           | …
```
=> Update cloud-init GOSC complete message when version >= 23.1

linux/deploy_vm/rebuild_unattend_install_iso.yml
Problem:
2023-03-23 09:29:13,023 | TASK [deploy_vm_bios_lsilogic_vmxnet3][Check VMware Tools is running and collects guest OS fullname successfully] 
task path: /home/worker/workspace/Ansible_Ubuntu_20.04_Desktop_ISO_70U3_LSILOGIC_VMXNET3_BIOS/ansible-vsphere-gos-validation/common/vm_wait_guest_fullname.yml:46
"assertion": "vm_guestinfo.instance.guest.toolsRunningStatus == \"guestToolsRunning\"",
"msg": "It's timed out for VMware Tools collecting guest OS fullname in 300 seconds. Current VMware Tools running status is 'guestToolsNotRunning', and guest OS fullname is ''."
}
error message:
It's timed out for VMware Tools collecting guest OS fullname in 300 seconds. Current VMware Tools running status is …
=> [Ubuntu 20.04 desktop] Failed to deploy ubuntu 20.04.6 desktop VM with bios

linux/deploy_vm/reconfigure_vm_with_cloudinit.yml, linux/utils/shutdown.yml
**Problem:**
For Ubuntu 22.10 OVA:
TASK [Set command to shutdown guestOS] *****************************************
task path: /home/worker/workspace/Ansible_Regression_Ubuntu_22.10_OVA/ansible-vsphere-gos-validation/linux/utils/shutdown.yml:5
"msg": "The task includes an option with an undefined variable. The error was: 'guest_os_family' is undefined. 'guest_os_family' is undefined\n\nThe error appears to be in '/home/worker/workspace/Ansible_Regression_Ubuntu_22.10_OVA/ansible-vsphere-gos-validation/linux/utils/shutdown.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Shutdown VM via executing shutdown command in VM\n- name: \"Set command to shutdown guestOS\"\n  ^ …
=> fix issue: guest_os_family is undefined

common/set_current_testcase_facts.yml, common/test_rescue.yml, linux/deploy_vm/deploy_vm.yml, linux/deploy_vm/deploy_vm_from_iso.yml, linux/deploy_vm/deploy_vm_from_ova.yml, linux/deploy_vm/flatcar/reconfigure_flatcar_vm.yml, linux/deploy_vm/reconfigure_vm_with_cloudinit.yml, linux/setup/test_setup.yml, main.yml, plugin/ansible_vsphere_gosv_log.py, windows/deploy_vm/deploy_vm.yml, windows/deploy_vm/deploy_vm_from_iso.yml, windows/deploy_vm/deploy_vm_from_ova.yml, windows/setup/test_setup.yml
Changes in this fix will print test cases in order in results.log with a case index in front of them, so that it can distinguish different runs for same test case. And test case log folder will have same case index in front of folder name. 
If there are less than 10 test cases, case index will start from "1".
If there are 10 or more test cases, case index will starts from "01".
```
+------------------------------------------------------------------------------------------+
| Product | Version | Build    | Hostname or IP | Server Model                             |
+------------------------------------------------------------------------------------------+
| vCenter | 8.0.0   | 20519528 | x.x.x.x  |                                          | …
```
=> Update log plugin to support more than one test case runs

plugin/ansible_vsphere_gosv_log.py
Fixed the test case index
```
Test Results (Total: 2, Passed: 1, Skipped: 1, Elapsed Time: 00:01:39)
| ID | Name             |   Status  | Exec Time |
|  1 | deploy_vm        | * Skipped | 00:00:00  |
|  2 | check_ip_address |   Passed  | 00:01:12  |
```
=> [Log plugin] Fix align character for test case index

linux/check_os_fullname/check_os_fullname.yml, linux/utils/add_repo_from_baseurl.yml, windows/deploy_vm/execute_win_gosc.yml, windows/deploy_vm/get_pvscsi_driver.yml, windows/guest_customization/win_gosc_execution.yml, windows/network_device_ops/network_adapter_deviceops.yml, windows/utils/win_check_file_exist.yml, windows/utils/win_copy_file_from_local.yml, windows/utils/win_create_file.yml, windows/utils/win_execute_cmd.yml, windows/utils/win_get_physical_cpu_devcon.yml, windows/utils/win_wait_file_exist.yml, windows/utils/win_write_to_file.yml
[ansible-vsphere-gos-validation] Fix redirecting types and deprecation warnings
redirecting (type: action) ansible.builtin.win_copy to ansible.windows.win_copy
redirecting (type: modules) ansible.builtin.win_stat to ansible.windows.win_stat
redirecting (type: modules) ansible.builtin.win_file to ansible.windows.win_file
redirecting (type: callback) ansible.builtin.timer to ansible.posix.timer (Cannot find)
redirecting (type: modules) ansible.builtin.setup to ansible.windows.setup 
redirecting (type: filter) ansible.netcommon.hwaddr to ansible.utils.hwaddr
redirecting (type: modules) ansible.builtin.vmware_guest to community.vmware.vmware_guest 
There is one still exists.
redirecting (type: callback) ansible.builtin.timer to ansible.posix.timer
Verified with Qi, and make sure it is a …
=> Fix 370 redirecting types and deprecation warnings

autoinstall/Ubuntu/Server/user-data.j2
fix issue: unknown keyboard variable "us" for layout "us"
test result:
pass for ubuntu 23.04, 22.04 and 20.04 live server
=> [ubuntu 23.04 live server] fix issue: unknown keyboard variable "us" for layout "us"

linux/guest_customization/linux_gosc_start.yml, linux/vhba_hot_add_remove/wait_device_list_changed.yml
1. From Ubuntu 22.04, using `/usr/bin/rescan-scsi-bus.sh` to rescan scsi devices would lead to system crash. The issue is still not resolved by Ubuntu, so here uses workaround for Ubuntu >= 22.04.
2. Ubuntu 23.04 cloud-init GOSC took more than 5 minutes, so this fix increased the GOSC timeout to 10min.
```
Test Results (Total: 4, Passed: 4, Elapsed Time: 00:47:36)
+-------------------------------------------------------------+
| ID | Name                              | Status | Exec Time |
+-------------------------------------------------------------+
|  1 | deploy_vm_efi_paravirtual_vmxnet3 | Passed | 00:19:13  |
|  2 | gosc_cloudinit_dhcp               | Passed | 00:11:40  |
|  3 | gosc_cloudinit_staticip           | Passed | 00:11:39  |
|  4 | lsilogic_vhba_device_ops          | …
```
=> [Linux] Fix test issue for Ububuntu 23.04

linux/guest_customization/linux_gosc_workflow.yml
Fix cloud-init GOSC failed issues in Oracle Linux 8.7 and 9.1
=> [Linux] Upgrade cloud-init in Oracle Linux 8.7 and 9.1 for cloud-init GOSC

windows/deploy_vm/deploy_vm.yml, windows/deploy_vm/deploy_vm_from_iso.yml
1. Getting the guest OS build number before enabling VBS
2. Do not add key provider when key provider type is not defined.
=> [Windows] Fix variables undefined error during deploying VM

linux/utils/add_official_online_repo.yml
Photon OS 5.0 online repo photon.repo is able to use after GA. I removed it for testing pre releases, now add it back.
photon.repo: Include all of packages versions for the Photon OS release
photon-release.repo: Include packages for the GA release
photon-updates.repo: Include latest packages for the Photon OS release
We usually use photon-release.repo and photon-updates.repo for package installation. In case we might need to install some old package versions, it is better to have photon.repo enabled also. So add it back.
```
Photon_4.0_OVA:
- 'VMTOOLS: 12.2.0 ob-21223074'
- 'Guest os distribution: VMware Photon OS 4.0 x86_64'
- 'Hardware version: vmx-20'
- 'Config guest id: vmwarePhoton64Guest'
- 'Guestinfo guest id: vmwarePhoton64Guest'
- 'Guestinfo guest full name: VMware Photon OS …
```
=> Add back VMware Photon OS 5.0 online repo photon.repo

linux/open_vm_tools/install_ovt.yml
By default Debian's online repo is not enabled, which could lead to installing open-vm-tools dependencies failure.
This change is to enable it so that it won't block open-vm-tools installation due to missing of dependencies.
=> Enable Debian online repo for installing open-vm-tools dependencies

README.md, changelogs/changelog.yml, docker_file/Dockerfile
=> Update changelogs, README and Dockerfile for v2.3 release

common/add_vsphere_hosts_in_inventory.yml, common/vcenter_get_domain_user_info.yml, common/vcenter_manage_domain_user.yml, env_setup/env_setup.yml, linux/open_vm_tools/ovt_verify_install.yml, linux/open_vm_tools/ovt_verify_status.yml, linux/open_vm_tools/ovt_verify_uninstall.yml, linux/open_vm_tools/uninstall_ovt.yml, linux/utils/add_user.yml, linux/utils/collect_cloudinit_logs.yml, linux/utils/collect_vgauth_logs.yml, linux/utils/enable_vgauth_logging.yml, linux/utils/enable_vmtools_logging.yml, linux/utils/set_ovt_facts.yml, linux/utils/set_vgauth_facts.yml, linux/vgauth_check_service/vgauth_check_service.yml, vars/test.yml, windows/utils/win_collect_vgauth_logs.yml, windows/utils/win_enable_vgauth_log.yml
This fix includes:
1. added common tasks to gather or manage vCenter Server domain user
2. enabled VGAuthService debug logging on Linux and Windows guest OS
3. collected VGAuthService log file on Linux and Windows guest OS
=> Add vars and tasks to support VGAuth guest operation testing

common/collect_ovf_vm_config.yml, linux/deploy_vm/deploy_vm_from_ova.yml, windows/deploy_vm/deploy_vm_from_ova.yml
From John:
Can you please check to see if our testing of OVAs includes verification of vmdk that ddb.toolsVersion is set to 2147483647 if open-vm-tools is included?  If we are not doing this then please add as a candidate new test.  I think the check needs to be done without booting the VM to be valid.
Test result: 
1) test with ubuntu 23.04 OVA:
2) test with photon 5.0 OVA
=> Check VMware Tools version after OVA/OVF deployment without poweron

linux/nvdimm_cold_add_remove/nvdimm_cold_add_remove.yml, linux/secureboot_enable_disable/check_secureboot_support_status.yml, linux/utils/get_installed_packages.yml, linux/utils/get_linux_system_info.yml, linux/utils/get_os_edition.yml, linux/utils/install_uninstall_package.yml
Skip secureboot_enable_disable for Pardus, UOS, ProLinux.
Skip nvdimm_cold_add_remove for UOS, Amazon Linux and Ubuntu Cloud Image.
=> Skip secureboot and nvdimm testing for guest OS not supporting them

windows/utils/win_enable_vbs_guest.yml
Enable Windows Defender Credential Guard:
Go to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa.
Add a new DWORD value named LsaCfgFlags. Set the value of this registry setting to 1 to enable Windows Defender Credential Guard with UEFI lock, set it to 2 to enable Windows Defender Credential Guard without lock, and set it to 0 to disable it.
=> [Windows]Enable Credential Guard for Windows Server

linux/deploy_vm/deploy_vm_from_iso.yml
**Issue:**
The cdrom is the first boot disk in boot order when create VM with firmware efi and install guestOS with ubuntu 23.04 desktop iso.
So it will hit the following issue if we mount iso and then reboot VM:
2023-04-22 03:48:04,022 | TASK [3_vmlibrary_main][Check VMware Tools is running and collects guest IPv4 address successfully] 
task path: /home/worker/workspace/Create_New_VMLibrary_Template/ansible-vsphere-gos-validation/common/vm_wait_guest_ip.yml:49
"assertion": "vm_guestinfo.instance.guest.toolsRunningStatus == \"guestToolsRunning\"",
"msg": [
"It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds.",
"VMware Tools running status is 'guestToolsNotRunning'.",
"VM's IP address in …
=> Change the boot disk to be first in boot order for ubuntu 23.04 desktop after deploy_vm

README.md, autoinstall/README.md, autoinstall/openSUSE/15/autoinst.xml, linux/check_os_fullname/check_os_fullname.yml, linux/deploy_vm/deploy_vm_from_iso.yml, linux/guest_customization/check_gosc_support_status.yml, linux/nvdimm_cold_add_remove/nvdimm_cold_add_remove.yml
- openSUSE Leap is a classic stable distribution approach, 15.3 completely based on SLE's binary packages. 
- This change added an autoinst.xml file for openSUSE autoinstall and fixed the testcase failures.
- Tested openSUSE 15.3/15.5 with lsilogic/lsilogicsas/sata/ide/pvscsi/nvme, vmxnet3/e1000e, efi/bios and passed.
- openSUSE 15.3:
```
+---------------------------------------------------------------+
| Name                      | test_vm                           |
+---------------------------------------------------------------+
| Guest OS Distribution     | openSUSE Leap 15.3 x86_64         |
+---------------------------------------------------------------+
| GUI Installed             | True                              | …
```
=> [New Feature][openSUSE] Support openSUSE autoinstall

common/vm_create.yml
With multiple clusters under same datacenter, we need to add parameter "esxi_hostname" or "cluster name" to common task vm_create.yml to specify the the esxi_hostname/cluster. Here uses `esxi_hostname` for creating VM.
=> Add parameter esxi_hostname to vm_create

README.md, autoinstall/Debian/10/preseed.cfg, autoinstall/README.md, common/get_guest_system_info.yml, linux/deploy_vm/deploy_vm_from_iso.yml, linux/guest_customization/check_gosc_support_status.yml, linux/utils/enable_disable_cloudinit_cfg.yml, linux/utils/get_linux_system_info.yml, linux/vhba_hot_add_remove/wait_device_list_changed.yml
Debian 12.0 ISO images doesn't have open-vm-tools builtin. So it needs to install open-vm-tools from online repo. In this fix,
1. Added some debug messages in preseed late_command
2. If the Debian ISO image have open-vm-tools builtin, install open-vm-tools from CDROM; otherwise, install it from online repo.
3. Install testing required packages during OS installation.
Test results
```
- 'Guest os distribution: Debian 10 i386'
- 'Hardware version: vmx-20'
- 'Config guest id: debian10Guest'
- 'Guestinfo guest id: debian10Guest'
- 'Guestinfo guest full name: Debian GNU/Linux 10 (32-bit)'
- 'Guestinfo guest family: linuxGuest'
- 'Guestinfo detailed data: architecture=''X86'' bitness=''32'' distroAddlVersion=''10
(buster)'' distroName=''Debian GNU/Linux'' distroVersion=''10'' …
```
=> [Linux] Fix Debian 12 auto installation failure

linux/deploy_vm/reconfigure_vm_with_cloudinit.yml
remove cdrom ISO before running "gosc_cloudinit_dhcp" & gosc_cloudinit_staticip in Ubuntu OVA package
**Test result:**
1) for ubuntu 23.04 OVA
2) for ubuntu 22.04 OVA
3) After running full testing for ubuntu 22.04 and 23.04 OVA, removing  cdrom ISO won't produce new issue.
Best regards
Yuhua Zou
=> [ansible-vsphere-gos-validation] Remove cdrom ISO before running cloud-init GOSC test cases for Ubuntu OVA

linux/deploy_vm/templates/photon-ova-user-data.j2, linux/guest_customization/check_gosc_log.yml, linux/guest_customization/linux_gosc_execution.yml, linux/guest_customization/linux_gosc_start.yml, linux/guest_customization/linux_gosc_workflow.yml, linux/utils/collect_cloudinit_logs.yml, linux/utils/enable_disable_cloudinit_cfg.yml
When enabling and starting cloud-init services on Ubuntu with latest cloud-init version, it will cause network interface down. By consulting with GOSC team, it is suggested to only enable but no start cloud-init services when enabling cloud-init GOSC.
On Photon OS OVA deployment, installing latest chrony will also lead to cloud-init service failure. As chrony won't affect Photon OS testing, so this fix removed it from Photon OS OVA's user data.
Besides, to gain more information to debug GOSC failures, this fix adjusted GOSC testing workflow, which will always collect tools deploypkg log for both perl GOSC and cloud-init, cloud-init config and logs for cloud-init GOSC.
And some ansible-lint errors were also fixed.
=> [Linux] Fix cloud-init GOSC failure on Ubuntu and Photon OS

windows/deploy_vm/create_unattend_install_iso.yml, windows/deploy_vm/get_ansible_remote_config.yml
https://github.com/ansible/ansible/pull/81011 removed examples folder from `ansible:devel` branch and moved to `ansible-documentation:devel` branch. So this fix updated the URL to get this PS1 script.
=> [Windows] Update URL for downloading ConfigureRemotingForAnsible.ps1

autoinstall/Photon/ks.cfg
Latest Photon OS 4.0 daily update couldn't recognize 'install_linux_esx' for ISO auto install. Photon OS team suggests replacing it with `"linux_flavor": "linux-esx"`.
```
- 'Guest os distribution: VMware Photon OS 4.0 x86_64'
- 'Hardware version: vmx-21'
- 'Config guest id: vmwarePhoton64Guest'
- 'Guestinfo guest id: vmwarePhoton64Guest'
- 'Guestinfo guest full name: VMware Photon OS (64-bit)'
- 'Guestinfo guest family: linuxGuest'
- 'Guestinfo detailed data: architecture=''X86'' bitness=''64'' distroName=''VMware
Photon OS'' distroVersion=''4.0'' familyName=''Linux'' kernelVersion=''5.10.83-7.ph4-esx''
prettyName=''VMware Photon OS/Linux'''
- 'Results: Total (2), Passed (2)'
- ' * deploy_vm_efi_paravirtual_vmxnet3...............................Passed'
- ' * …
```
=> [Linux] Replace install_linux_esx with linux_flavor for Photon OS autoinstall

linux/check_quiesce_snapshot_custom_script/check_quiesce_snapshot_custom_script.yml, linux/guest_customization/check_gosc_support_status.yml, linux/network_device_ops/apply_new_network_config.yml, linux/network_device_ops/check_pvrdma_support_status.yml, linux/nvdimm_cold_add_remove/nvdimm_cold_add_remove.yml, linux/open_vm_tools/ovt_verify_install.yml, linux/open_vm_tools/ovt_verify_status.yml, linux/open_vm_tools/ovt_verify_uninstall.yml, linux/utils/get_network_config_file.yml, linux/utils/get_network_manager.yml, linux/vgauth_check_service/vgauth_check_service.yml, linux/vhba_hot_add_remove/vhba_device_hot_add_remove.yml, linux/vhba_hot_add_remove/wait_device_list_changed.yml
https://github.com/ansible/ansible/pull/77635 flatcar distribution name has been fixed in ansible-core 2.14. Now its guest_os_ansible_distribution is 'Flatcar' not 'Flatcar Container Linux by Kinvolk' any more.
=> Update checking guest_os_ansible_distribution is Flatcar

common/vm_create.yml
If there is no vcenter_hostname defined in vars/test.yml, vsphere_host_name will be same with esxi_hostname, and `common/vm_create.yml` will report error like "Unable to find host". It means that esxi_hostname is required when vsphere_host_name = vcenter_hostname for this task. The solution is to ignore esxi_hostname when vsphere_host_name = esxi_hostname.
=> Ignore esxi_hostname at VM creation when vcenter_hostname is not defined

linux/utils/check_guest_os_gui.yml, linux/utils/set_ovt_facts.yml
```
- 'Guest os distribution: Ubuntu 20.04 Server x86_64'
- 'Config guest id: ubuntu64Guest'
- 'Guestinfo guest id: ubuntu64Guest'
- 'Guestinfo guest full name: Ubuntu Linux (64-bit)'
- 'Guestinfo guest family: linuxGuest'
- 'Guestinfo detailed data: architecture=''X86'' bitness=''64'' distroAddlVersion=''20.04.6
LTS (Focal Fossa)'' distroName=''Ubuntu'' distroVersion=''20.04'' familyName=''Linux''
kernelVersion=''5.4.0-144-generic'' prettyName=''Ubuntu 20.04.6 LTS'''
- 'Results: Total (3), Passed (3)'
- ' * deploy_vm_efi_paravirtual_vmxnet3...............................Passed'
- ' * ovt_verify_install..............................................Passed'
- ' * ovt_verify_status...............................................Passed'
- 'Guest os distribution: VMware Photon OS 3.0 x86_64'
- …
```
=> [Linux] Correct ovt_packages for Linux guest OS with desktop

autoinstall/BCLinux-for-Euler/21.10/ks.cfg, autoinstall/BCLinux/8/ks.cfg, autoinstall/CentOS/7/ks.cfg, autoinstall/CentOS/7/minimal/ks.cfg, autoinstall/Debian/10/preseed.cfg, autoinstall/Fedora/36/Server/ks.cfg, autoinstall/FreeBSD/installerconfig, autoinstall/Pardus/preseed.cfg, autoinstall/RHEL/7/server_with_GUI/ks.cfg, autoinstall/RHEL/7/server_without_GUI/ks.cfg, autoinstall/RHEL/8/server_with_GUI/ks.cfg, autoinstall/RHEL/8/server_without_GUI/ks.cfg, autoinstall/SLE/15/SP3/SLED/autoinst.xml, autoinstall/SLE/15/SP3/SLES/autoinst.xml, autoinstall/SLE/15/SP3/SLES_Minimal/autoinst.xml, autoinstall/SLE/15/SP4/SLED/autoinst.xml, autoinstall/UOS/Server/20/1050a/ks.cfg, autoinstall/UOS/Server/20/1050e/ks.cfg, autoinstall/Ubuntu/Desktop/Subiquity/user-data.j2, autoinstall/Ubuntu/Desktop/Ubiquity/ubuntu.seed, autoinstall/Ubuntu/Server/user-data.j2, autoinstall/openSUSE/15/autoinst.xml, linux/deploy_vm/delete_unattend_install_iso.yml, linux/deploy_vm/deploy_vm_from_iso.yml, linux/deploy_vm/eject_del_unattend_install_iso.yml, linux/deploy_vm/rebuild_photon_unattend_install_iso.yml, linux/deploy_vm/rebuild_ubuntu_unattend_install_iso.yml, linux/utils/shutdown.yml
Even though guest OS sends autoinstall complete message to serial port, it might still be running some post tasks and it won't be rebooted immediately. Sometimes the post tasks take some time, which led to ansible tasks thought starting to wait for guest full name but it failed due to guest OS hasn't reboot at all. 
It is difficult to find the best timing when to wait for guest full name, so in this change I replaced 'reboot' with 'shutdown' as the following action after autoinstall is compeleted. Therefore, we only needs to wait for VM's power states becoming poweredOff after autoinstall complete message received. Then we can consider the complete autoinstall process is finished, and then power on VM to wait for its guest full name.
In this change, I also added boot options for …
=> [Linux] Shutdown guest OS after auto install completes instead of rebooting

common/vm_revert_snapshot.yml
We need to capture the error message while reverting VM snapshot failed, and print it into failed_tasks.log.
```
TASK [Display revert snapshot result] **************************************************************************************************************************************
task path: /home/qiz/workspace/github/ansible-vsphere-gos-validation/common/vm_revert_snapshot.yml:29
"revert_result": {
"failed": true,
"msg": "The operation cannot be allowed at the current time because the virtual machine has a question pending: \n 'msg.hbacommon.outofspace:There is no more space for virtual disk 'Ansible_winsrv_vbs_80ga-000003.vmdk'. You might be able to continue this session by freeing disk space on the relevant volume, and clicking Retry. Click …
```
=> Print error message when reverting VM snapshot failed

common/test_rescue.yml, linux/nvdimm_cold_add_remove/cold_add_nvdimm_test.yml, linux/utils/freebsd_get_geom_conf_xml.yml, linux/utils/freebsd_get_partition_info.yml, linux/vhba_hot_add_remove/freebsd_create_disk_partition.yml, linux/vhba_hot_add_remove/hot_add_remove_disk.yml, linux/vhba_hot_add_remove/test_file_read_write.yml, linux/vhba_hot_add_remove/vhba_device_hot_add_remove.yml
The device boot order might be changed when adding new controller and disk to BIOS VM after reboot. So before vHBA testing, we need to set VM's boot order and make its boot disk as the first boot device, then we can enable file read/write after hot adding a new disk and reboot.
=> [Linux] Set VM boot order before vHBA testing and test file read/write on new disk

common/vm_remove_network_adapter.yml, linux/network_device_ops/hot_remove_network_adapter.yml, windows/network_device_ops/network_adapter_deviceops.yml
Oracle Linux 8.8 PVRDMA testing might fail on ESXi 7.0.x because of a known issue described in KB https://kb.vmware.com/s/article/93131. To reduce triage time, I added a known issue for it. As the resolution is to upgrade ESXi version, we can workaround it in our test case. So the test case will still fail but print out a known issue.
Test result:
```
+------------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                               |
|                           | bitness='64'                                     |
|                           | distroName='Oracle Linux Server'                 |
|                           | distroVersion='8.8'                              |
|                           | …
```
=> [Linux] Add known issue for PVRDMA hot-remove failure on Oracle Linux 8.8

README.md, autoinstall/Pardus/preseed.cfg, linux/network_device_ops/apply_new_network_config.yml, linux/utils/get_network_config_file.yml, linux/utils/get_network_manager.yml
Task:
Support ansible testcases for Pardus 21.x
Test result:
1. For pardus 21.5 XFCE
2. For pardus 21.2 Server:
Note:
For the failed testcases, it's 3rd issues
=> [Pardus] Support ansible testcases for Pardus 21.x

autoinstall/Pardus/preseed.cfg, linux/vhba_hot_add_remove/wait_device_list_changed.yml
Issue:
The official repo is changed in pardus 23.0 which cause the failure to install packages during autoinstall.
Test result:
=> [Pardus] the offical repo is changed for pardus 23.0

common/collect_ovf_vm_config.yml, plugin/ansible_vsphere_gosv_log.py
The hardware version in collected OVF config info is empty without this fix, as below:
```
"ovf_vm_hardware_config": {
"CPU Cores per Socket": 1,
"CPU Hot Add Enabled": false,
"CPU I/O MMU": false,
"CPU Nested HV Enabled": false,
"CPU Number": 2,
"Firmware": "efi",
"Guest OS ID": "rhel8_64Guest",
"Guest OS Version": "Red Hat Enterprise Linux 8 (64-bit)",
"Hardware Version": "",
"Memory Hot Add Enabled": false,
"Memory Size in MB": 4096,
"Secure Boot": false,
"VBS Enabled": false,
"Virtual TPM": false
}
```
With this fix:
```
"ovf_vm_hardware_config": {
"CPU Cores per Socket": 1,
"CPU Hot Add Enabled": false,
"CPU I/O MMU": false,
"CPU Nested HV Enabled": false,
"CPU Number": 2,
"Firmware": "efi",
"Guest OS ID": "rhel8_64Guest",
"Guest OS Version": "Red Hat Enterprise Linux 8 (64-bit)", …
```
=> Fix empty hardware version in collected OVF config info and guest_info.json

linux/check_os_fullname/check_os_fullname.yml
When test failed at test_setup, it won't define `vmtools_log_dir`, but at always block, this var is used. So here needs to check `vmtools_log_dir` is defined.
=> [Linux] Check vmtools_log_dir is defined before using in check_os_fullname

autoinstall/FreeBSD/13/installerconfig, autoinstall/FreeBSD/14/installerconfig, autoinstall/FreeBSD/installerconfig, autoinstall/README.md, linux/deploy_vm/deploy_vm_from_iso.yml
The nvme disk name in FreeBSD 13 is nvd0, but in FreeBSD it is changed to nda0.
We need to change autoinstall for FreeBSD 14.
Test result:
=> [FreeBSD 14] The default nvme disk name is changed in FreeBSD 14 which cause the failure for autoinstall

common/esxi_get_guest_config_options.yml, common/esxi_get_guest_ids.yml, common/esxi_get_hardware_versions.yml
Fix #440 
Getting hardware versions:
```
2023-09-19 20:00:11,019 | TASK [test_debug][Display ESXi server supported hardware versions] 
task path: /home/qiz/workspace/github/ansible-vsphere-gos-validation/common/esxi_get_hardware_versions.yml:43
ok: [localhost] => { 
"msg": [
"ESXi server supported hardware versions: [4, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]",
"ESXi server latest hardware version: 17", 
"ESXi server default hardware version: 17"
]    
}
```
Tested with ESXi 7.0GA, getting guest ids and guest config options from xml file:
```
2023-09-19 20:00:16,019 | TASK [test_debug][Print ESXi server supported guest IDs on hardware version 17]
task path: /home/qiz/workspace/github/ansible-vsphere-gos-validation/common/esxi_get_guest_ids.yml:65
"esxi_guest_ids": [ …
```
=> Fix dict item names in community.vmware.vmware_vm_config_option result

linux/check_inbox_driver/check_inbox_driver.yml, linux/utils/freebsd_get_partition_info.yml, linux/vgauth_check_service/vgauth_check_service.yml
If test case fails at test_setup, some variables used in rescue or always block may be not defined but used, which would lead to variable undefined error. This fix is to add conditions to use those variables.
=> [Linux] Fix undefined variables at rescue or always block when test_setup failed

linux/check_os_fullname/validate_os_fullname.yml
Fix check_os_fullname for Flatcar on ESXi 7.0GA.
```
+---------------------------------------------------------------------------------------------------------+
| Guest OS Distribution     | Flatcar 3602.2.0 x86_64                                                     |
+---------------------------------------------------------------------------------------------------------+
| GUI Installed             | False                                                                       |
+---------------------------------------------------------------------------------------------------------+
| CloudInit Version         |                                                                             |
+-------------------------------------------------------------------------------------------------- …
```
=> [Linux] Update known issue condition for unmapped guest full name

autoinstall/FreeBSD/13/installerconfig, autoinstall/FreeBSD/14/installerconfig
Issue:
----------------
2023-10-12 03:58:05,012 | TASK [2_ovt_verify_status][Check process 'vmtoolsd -n vmusr' is running] 
task path: /home/worker/workspace/Ansible_Cycle_FreeBSD_13.x_64bit/ansible-vsphere-gos-validation/linux/utils/check_process_status.yml:34
"assertion": "running_process_info | length >= 1",
"msg": "User 'vmware' doesn't have running process 'vmtoolsd -n vmusr'"
}
error message:
User 'vmware' doesn't have running process 'vmtoolsd -n vmusr'
Root Cause
-----------------------
KDE5 is installed from ISO with use Qt library (5.15.8)
SDDM is installed from offical repo which use Qt (5.15.10)
The service SDDM is failed to start during bootup.
Check the sddm log: (/var/log/sddm.log)
[05:49:38.184] (II) …
=> [FreeBSD 13] Cannot mix incompatible Qt library (5.15.8) with this library (5.15.10)

linux/guest_customization/wait_gosc_complete_msg.yml
Cloud-init GOSC with static IP address on Ubuntu 23.10 took more than 100s to finish. So this change increased the default timeout to 300s.
=> Increase time out for waiting Linux GOSC finished message

README.md, autoinstall/FusionOS/server_with_GUI/ks.cfg, autoinstall/FusionOS/server_without_GUI/ks.cfg, autoinstall/README.md, linux/deploy_vm/deploy_vm_from_iso.yml, linux/secureboot_enable_disable/check_secureboot_support_status.yml
- This change added autoinstall support and necessary test updates for FusionOS 22 and 23. 
- Tested FusionOS 22 and 23 with sata/ide/pvscsi/nvme, vmxnet3/e1000e, efi/bios and all passed except known issues.
```
+---------------------------------------------------------------------------------+
| Guest OS Distribution     | FusionOS 23.0.1 x86_64                              |
+---------------------------------------------------------------------------------+
| GUI Installed             | False                                               |
+---------------------------------------------------------------------------------+
| CloudInit Version         | 21.4                                                |
+------------------------------------------------------------------- …
```
=> Add support for FusionOS 22 and 23

README.md, linux/check_os_fullname/miracle_fullname_map.yml, linux/check_os_fullname/set_guestinfo_without_shortname.yml
Issue:
check_os_fullname failed for MiracleLinux-8.x with latest VMware Tools
detail info:
2023-10-11 12:34:17,011 | TASK [1_check_os_fullname][Check guest id in VM's guest info with VMware Tools 12.4.0 on ESXi 8.0.0]
task path: /home/worker/workspace/Ansible_MiracleLinux_8.x_80GA_PARAVIRTUAL_VMXNET3_EFI/ansible-vsphere-gos-validation/linux/check_os_fullname/validate_os_fullname.yml:56
"assertion": "guestinfo_guest_id == expected_guest_id",
"msg": "VM's guest id in guest info is 'asianux8_64Guest', not expected 'other4xLinux64Guest'."
}
=> [MiracleLinux] check_os_fullname failed for MiracleLinux-8.x with latest VMware Tools

README.md, autoinstall/Debian/10/preseed.cfg, autoinstall/Pardus/preseed.cfg, autoinstall/Ubuntu/Desktop/Ubiquity/ubuntu.seed, common/delete_local_file.yml, common/vm_get_video_card.yml, common/vm_set_video_card.yml, linux/deploy_vm/collect_vm_logs.yml, linux/deploy_vm/create_unattend_install_conf_file.yml, linux/deploy_vm/create_unattend_install_iso.yml, linux/deploy_vm/delete_unattend_install_iso.yml, linux/deploy_vm/deploy_vm.yml, linux/deploy_vm/deploy_vm_from_iso.yml, linux/deploy_vm/deploy_vm_from_ova.yml, linux/deploy_vm/rebuild_debian_unattend_install_iso.yml, linux/deploy_vm/rebuild_pardus_unattend_install_iso.yml, linux/deploy_vm/rebuild_ubuntu_unattend_install_iso.yml, linux/deploy_vm/rebuild_unattend_install_iso.yml, linux/deploy_vm/reconfigure_vm_with_cloudinit.yml, linux/deploy_vm/templates/post_install_scripts/add_pardus_repo.sh, linux/deploy_vm/templates/post_install_scripts/apt_install_pkgs.sh, linux/deploy_vm/templates/post_install_scripts/config_ssh.sh, linux/deploy_vm/templates/post_install_scripts/disable_greeter.sh, linux/deploy_vm/templates/post_install_scripts/disable_screen_saver.sh, linux/deploy_vm/templates/post_install_scripts/enable_auto_login.sh, linux/deploy_vm/templates/post_install_scripts/get_os_info.sh, linux/deploy_vm/templates/post_install_scripts/preseed_late_command.sh, linux/deploy_vm/templates/post_install_scripts/set_locale.sh, linux/deploy_vm/templates/pre_install_scripts/preseed_early_command.sh, linux/utils/create_seed_iso.yml
We need more information to identify OS deployment failure when not detecting "Autoinstall is completed" message. This fix made some changes to OS using Debian installer like Debian, Pardus, Ubuntu desktop 22.10 or earlier (which uses Ubiquity).
1. Added separate shell scripts to be executed at early_command and late_command/success_command, which are more easier to maintain and identify script errors.
2. Added early command to print some basic information, like environment variables, IP address (might be empty, which is as expected for most of Debian family OS), boot command (we can see whether boot command options are correct at debug)
3. Dump /var/log/syslog to serial console after installation, which is the full installer log.
4. Optimized …
=> [Linux] Print more installer logs for Debian installer at early and late commands

windows/wintools_complete_install_verify/install_vmtools.yml, windows/wintools_complete_install_verify/wintools_complete_install_verify.yml
The default value for ANSIBLE_WIN_ASYNC_STARTUP_TIMEOUT is 5s. This can be too low on slower systems, or systems under heavy load. Increase the value to 10 seconds for VMware Tools installation which encountered such issue before.
=> [Windows] Change the default value for ANSIBLE_WIN_ASYNC_STARTUP_TIMEOUT to 10 sencods when installing VMware Tools

common/test_rescue.yml, linux/memory_hot_add_basic/memory_hot_add_basic.yml
Fix issue: memory_hot_add_basic: 'current_testcase_name' is undefined at test_rescue
2023-11-17 01:56:22,017 | Failed at Play [1_memory_hot_add_basic] ********************
2023-11-17 01:56:22,017 | TASK [1_memory_hot_add_basic][Skip testcase: memory_hot_add_basic, reason: Blocked] 
task path: /home/worker/workspace/Ansible_OracleLinux_9.x_70U1_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/skip_test_case.yml:21
fatal: [localhost]: FAILED! => Test case 'memory_hot_add_basic' is blocked because memory hotadd test value list is empty
error message:
Test case 'memory_hot_add_basic' is blocked because memory hotadd test value list is empty
2023-11-17 01:56:22,017 | TASK [1_memory_hot_add_basic][Print failed test case] ******
task path: …
=> Fix issue: memory_hot_add_basic: 'current_testcase_name' is undefined at test_rescue

autoinstall/SLE/15/SP4/SLED/autoinst.xml, linux/deploy_vm/create_unattend_install_iso.yml, linux/deploy_vm/deploy_vm_from_iso.yml
There is module conflicts when resolving packages dependencies. So this fix removed not necessary modules and packages at deploy_vm.  Besides, the default 4MB video memory is not enough to launch SLED 15 SP6 desktop. So VM's video memory will be increased to 8MB for RHEL/SLE with desktop installed.
=> [Linux] Fix autoinstall issue for SLED 15 SP6 Beta2

linux/secureboot_enable_disable/check_secureboot_support_status.yml, linux/secureboot_enable_disable/secureboot_enable_disable.yml
test result:
For miraclelinux 8.8:
For miraclelinux 9:
=> set secureboot_enable_disable as not supported for MiracleLinux-8.x

common/vm_get_vm_info.yml, common/vm_wait_primary_nic_mac.yml, env_setup/env_setup.yml, linux/deploy_vm/deploy_vm_from_iso.yml, linux/deploy_vm/deploy_vm_from_ova.yml, windows/deploy_vm/deploy_vm_from_iso.yml, windows/deploy_vm/deploy_vm_from_ova.yml
The VM might not have MAC address after vm_create.yml, which led to vm_primary_nic_mac not set and failing to get VM IP. Changes in this PR fixes this issue.
=> Get VM primary mac address after VM power on

changelogs/changelog.yml, windows/eflow_deploy/deploy_eflow_vm.yml, windows/utils/win_create_vswitch.yml, windows/utils/win_enable_client_hyperv.yml, windows/utils/win_enable_server_hyperv.yml, windows/utils/win_execute_cmd.yml, windows/utils/win_get_disk_size.yml, windows/utils/win_get_ethernet_name.yml, windows/utils/win_get_set_disk_online.yml, windows/utils/win_get_sub_files_folders.yml, windows/utils/win_pause_windows_update.yml, windows/utils/win_wait_service_status.yml
Change word "powershell" to "PowerShell" in the task name, debug message and description part etc.
=> Change word powershell to PowerShell

autoinstall/FusionOS/server_with_GUI/ks.cfg, autoinstall/FusionOS/server_without_GUI/ks.cfg, vars/test.yml
Added below 4 variables to configure static IP at deploy_vm for FusionOS.
```
```
After autoinstall completes, the network interface is successfully configured with static IP:
Nameservers are set:
```
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=none
IPADDR=x.x.x.x
PREFIX=20
GATEWAY=x.x.x.x
DNS1=x.x.x.x
DNS2=x.x.x.x
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=ens33
UUID=e3d3aa8b-76ad-4104-b06e-8ed5e1e12245
DEVICE=ens33
ONBOOT=yes
```
Nameservers are not set:
```
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=none
IPADDR=x.x.x.x
PREFIX=20
GATEWAY=x.x.x.x
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no …
```
=> [Linux] Add variables for installing FusionOS with static IP address

linux/check_os_fullname/check_os_fullname.yml, linux/check_quiesce_snapshot_custom_script/check_quiesce_snapshot_custom_script.yml, linux/utils/collect_vmtools_logs.yml, linux/vgauth_check_service/vgauth_check_service.yml
From Flatcar 3760.2.0, /etc/vmware-tools is not writable any more. So we can't enable VMware Tools debug logs in /etc/vmware-tools/tools.conf, and can't create quiesce snapshot scripts under /etc/vmware-tools/backupScripts.d. Besides, Flatcar 3760.2.0 added vgauth. Therefore, I made below changes for Flatcar:
1. Do not enable VMware Tools debug logging for Flatcar 3760.2.0 or later, and only collect default VMware Tools logs from /var/log.
2. Skip check_quiesce_snapshot_custom_script testing from Flatcar 3760.2.0.
3. Check VGAuth service status from Flatcar 3760.2.0.
In Flatcar 3760.2.0, vmtoolsd and vgauthd services are running but disabled. That need to double check with Flatcar whether it is a 3rd party issue.
``` …
```
=> [Linux] Fix test issue for Flatcar 3760.2.0

common/reset_base_snapshot.yml, common/set_current_testcase_facts.yml, common/test_rescue.yml, common/vcenter_add_key_provider.yml, common/vm_add_serial_port.yml, linux/check_os_fullname/check_os_fullname.yml, linux/check_quiesce_snapshot_custom_script/check_quiesce_snapshot_custom_script.yml, linux/deploy_vm/create_unattend_install_iso.yml, linux/deploy_vm/deploy_vm.yml, linux/deploy_vm/reconfigure_vm_with_cloudinit.yml, linux/network_device_ops/pvrdma_network_device_ops.yml, linux/utils/collect_cloudinit_logs.yml, linux/utils/create_seed_iso.yml, linux/utils/enable_vgauth_logging.yml, linux/vhba_hot_add_remove/lsilogic_vhba_device_ops.yml, linux/vhba_hot_add_remove/lsilogicsas_vhba_device_ops.yml, linux/vhba_hot_add_remove/nvme_vhba_device_ops.yml, linux/vhba_hot_add_remove/paravirtual_vhba_device_ops.yml, linux/vhba_hot_add_remove/sata_vhba_device_ops.yml, windows/check_quiesce_snapshot/check_quiesce_snapshot.yml, windows/deploy_vm/create_unattend_install_iso.yml, windows/deploy_vm/gen_unattend_xml_file.yml, windows/vtpm_cold_add_remove/vtpm_add_remove_test.yml, windows/wintools_uninstall_verify/add_new_vmxnet3_net_adapter.yml
Added a new variable `current_test_timestamp` for each test case, which can be used to replace expressions like `{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}`.
=> Add current_test_timestamp at test_setup as a common variable

common/vm_remove_snapshot.yml
When there's one snapshot and need to be removed, will hit error "'dict object' has no attribute"
=> Fix snapshot remove null error

autoinstall/FreeBSD/13/installerconfig, autoinstall/FreeBSD/14/installerconfig, common/esxi_wait_portgroup.yml, common/test_rescue.yml, linux/deploy_vm/deploy_vm_from_ova.yml, linux/guest_customization/check_dns.yml
Fix regression test issues:
1. VM deployed from OVA's primary NIC mac is null after reverting snapshot. So reordered the task to get primary NIC mac after `collect_ovf_vm_config.yml` and `vm_get_vm_info.yml`.
2. `hostname_timestamp` was replaced by `current_test_timestamp`, which should be also replaced in unattend install config files.
3. esxi_wait_portgroup.yml returned host_portgroup_info is using ESXi hostname as its dictionary key not the value of `esxi_hostname`, which led to failure.
4. The guest OS's dns search domains might be in multiple lines after executing `resolvectl domain`. Updated the regex expression for getting the search domains and dns servers.
=> [Linux] Fix v3.1 regression test issues for deploy_vm, GOSC and waiting ESXi portgroup

linux/open_vm_tools/install_ovt.yml, linux/utils/add_local_dvd_repo.yml
Problem:
ovt_verify_install downgraded OVT from 12.2.5 to 12.1.5 in RockyLinux 8.9 and 9.3
Test Result:
1) Sanity check in RockyLinux 9.3
Check the setting about local DVD repo from output message:
=> [Linux] Add cdrom repo when testing ovt_verify_install for Rocky Linux and AlmaLinux

README.md, autoinstall/README.md, linux/deploy_vm/rebuild_pardus_unattend_install_iso.yml, linux/deploy_vm/templates/post_install_scripts/apt_install_pkgs.sh
Problem
the autoinstall for pardus 23.1 server does not work.
Result:
1) for pardus 23.1 server:
2) For pardus 23.1 XFCE:
=> [Pardus 23.1 Server] fix autoinstall issue for pardus 23.1 server

windows/vbs_enable_disable/vbs_enable_disable.yml, windows/vbs_enable_disable/vbs_enable_test.yml
For different Windows releases, the value of AvailableSecurityProperties is different.
=> [Windows]Set AvailableSecurityProperties for different OS versions

linux/open_vm_tools/ovt_verify_status.yml, linux/utils/check_process_status.yml, linux/utils/check_service_status.yml, linux/utils/get_systemd_unit_properties.yml, linux/vgauth_check_service/vgauth_check_service.yml
While testing Flatcar Stable 3760.2.0, we found that the default status of vmtoolsd.service and vgauthd.service were disabled, but they could start at boot. That is because they are started via a dependency in
/usr/lib/systemd/system/multi-user.target.d/open-vm-tools-sysext-upholds.conf. https://github.com/flatcar/Flatcar/issues/1330#issuecomment-1905544304 explains this change. 
So in our test cases, we need to checking whether vmtoolsd and vgauthd are in upholds of systemd unit multi-user.target for Flatcar. If they are in upholds, we can ignore their service status, no matter they are enabled or disabled.
=> [Linux] Skip vmtoolsd and vgauthd status checking when they are upheld in Flatcar

common/esxi_get_model.yml, common/esxi_get_property.yml, linux/deploy_vm/deploy_vm.yml, plugin/ansible_vsphere_gosv_log.py, tools/query_cpu.py, windows/deploy_vm/deploy_vm.yml
Added a script to query Intel CPU code name from Intel website, and display the ESXi model, CPU model information at deploy_vm failure. Failures on 70GA, 71U1 with Intel Skylake, Ice Lake, and Cascade Lake CPU, print known issue.
failed_tasks.log
```
2024-03-02 11:00:48,002 | Failed at Play [1_deploy_vm] *******************************
2024-03-02 11:00:48,002 | TASK [1_deploy_vm][Check VMware Tools is running and collects guest OS fullname successfully] 
task path: /home/qiz/workspace/github/ansible-vsphere-gos-validation/common/vm_wait_guest_fullname.yml:46
"assertion": "vm_guestinfo.instance.guest.toolsRunningStatus == \"guestToolsRunning\"",
"msg": "It's timed out for VMware Tools collecting guest OS fullname in …
```
=> Display ESXi model, CPU model and code name at deploy_vm failure

linux/guest_customization/check_gosc_support_status.yml, linux/guest_customization/gosc_support_matrix.yml, linux/guest_customization/linux_gosc_workflow.yml, linux/utils/get_linux_system_info.yml
**Task:**
Add the GOSC support matrix based on the following info:
1) If VM's config_guest_id = 'asianux8_64Guest' on 7.0.x, both perl and cloud-init GOSC should be skipped with reason 'Not Supported'.
2) On 8.0.x, perl GOSC for Miracle Linux 8.4 and later, 9.x are not supported on 8.0.2 or earlier.
3) It needs to update the version of cloud-init to 22.1 to support miraclelinux.
4) KB https://ikb.vmware.com/s/article/88600: Guest OS Customization for Miracle Linux 8 is not fully supported in vSphere 6.7 and 7.0 (88600)
**Test result:**
Testing is on-going.
=> [Linux] Update GOSC testing support status for Miracle Linux

linux/open_vm_tools/install_ovt.yml, linux/utils/add_local_dvd_repo.yml
**Issue:**
Raw Log:
2024-03-08 18:20:58,008 | Failed at Play [03_ovt_verify_install] *********************
2024-03-08 18:20:58,008 | TASK [03_ovt_verify_install][Assert command is executed successfully]
task path: /home/worker/workspace/Ansible_openSUSE_80GA_LSILOGICSAS_VMXNET3_BIOS/ansible-vsphere-gos-validation/linux/open_vm_tools/install_ovt.yml:46
fatal: [localhost]: FAILED! => Failed to install open-vm-tools by executing command: zypper install -y open-vm-tools open-vm-tools-desktop libvmtools0.
error message:
Failed to install open-vm-tools by executing command: zypper install -y open-vm-tools open-vm-tools-desktop libvmtools0."
**Resolution:**
Add DVD repo 
**Result**
=> [OpenSUSE Leap] ovt_verify_install failed on opensuse-15.6-BETA-64bit

common/esxi_get_model.yml, windows/vbs_enable_disable/vbs_enable_disable.yml, windows/vbs_enable_disable/vbs_enable_test.yml
Using Intel CPUs for VBS requires vSphere 6.7 or later (HW14)
Using AMD CPUs for VBS equires vSphere 7.0 Update 2 or later (HW19)
=> [Windows] Skip VBS test for guest OS with lower hardware version

linux/utils/disable_firewall.yml
RHCOS's ansible family is `RedHat`, but it doesn't have firewalld service. So here excluded it from firewall service setting. This change is to fix network_device_ops testing failure like below:
```
Raw Log:
2024-03-26 14:40:24,026 | Failed at Play [2_vmxnet3_network_device_ops] **************
2024-03-26 14:40:24,026 | TASK [2_vmxnet3_network_device_ops][Update service firewalld.service, enabled: False, state: stopped] 
task path: /home/worker/workspace/Ansible_Cycle_RHCOS_OVA/ansible-vsphere-gos-validation/linux/utils/service_operation.yml:17
fatal: [localhost -> x.x.x.x]: FAILED! => systemd could not find the requested service ""'firewalld.service'"": 
error message:
systemd could not find the requested service ""'firewalld.service'"":
```
Test passed with this fix
``` …
```
=> [RHCOS] Fix systemd could not find the requested service 'firewalld.service'

linux/deploy_vm/deploy_vm_from_iso.yml
Default video memory is only 4 MB, which could cause Ubuntu failed to launch the display manager. Increase it to 8MB.
```
+-------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                          |
|                           | bitness='64'                                |
|                           | distroAddlVersion='23.10 (Mantic Minotaur)' |
|                           | distroName='Ubuntu'                         |
|                           | distroVersion='23.10'                       |
|                           | familyName='Linux'                          |
|                           | kernelVersion='6.5.0-26-generic'            |
|                           | prettyName='Ubuntu 23.10' …
```
=> [Linux] Increase video memory to 8MB for Ubuntu desktop VM

common/get_guest_system_info.yml, linux/check_efi_firmware/check_efi_firmware.yml, linux/utils/get_system_firmware.yml
FreeBSD doesn't have `/sys/firmware/efi`, but can check `efirt` is loaded if system firmware is EFI. So, this fix is to set `guest_firmware` for FreeBSD.
Test passed:
```
+----------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'           |
|                           | bitness='64'                 |
|                           | distroName='FreeBSD'         |
|                           | familyName='FreeBSD'         |
|                           | kernelVersion='13.3-RELEASE' |
+----------------------------------------------------------+
Test Results (Total: 1, Passed: 1, Elapsed Time: 00:01:10)
+----------------------------------------------+
| ID | Name               | Status | Exec Time | …
```
=> [Linux] update get_system_firmware.yml to get system firmware for FreeBSD

linux/utils/disable_firewall.yml
Amazon Linux doesn't have firewalld.service either. So no need to disable firewalld.service on Amazon Linux.
```
+---------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                            |
|                           | bitness='64'                                  |
|                           | cpeString='cpe:2.3:o:amazon:amazon_linux:2'   |
|                           | distroAddlVersion='2'                         |
|                           | distroName='Amazon Linux'                     |
|                           | distroVersion='2'                             |
|                           | familyName='Linux'                            |
|                           | …
```
=> [Linux] Skip disabling firewalld.service for Amazon Linux

autoinstall/Photon/ks.cfg
The package list file "packages_ova.json" was removed from VMware Photon OS 5.0 daily build. This fix replaced it with "packages_minimal.json".
=> [Linux] Update packagelist_file in VMware Photon OS kickstart

README.md, autoinstall/README.md, linux/secureboot_enable_disable/check_secureboot_support_status.yml
Task:
support centOS Stream in ansible.
Result:
1) passed to test CentOS-Stream-9-x86_64-latest-dvd1.iso  with RHEL/8/server_with_GUI/ks.cfg and EFI firmware
2) passed to test CentOS-Stream-9-x86_64-latest-dvd1.iso  with RHEL/8/server_without_GUI/ks.cfg and EFI firmware
3) passed to test CentOS-Stream-9-x86_64-latest-dvd1.iso with RHEL/8/server_with_GUI/ks.cfg and bios firmware
4) passed to test CentOS-Stream-8-x86_64-latest-dvd1.iso  with RHEL/8/server_with_GUI/ks.cfg and bios firmware
5) passed to test CentOS-Stream-8-x86_64-latest-dvd1.iso  with RHEL/8/server_without_GUI/ks.cfg and EFI firmware
=> [CentOS Stream] support centOS Stream in ansible.

windows/windows_update_install/install_msu_file.yml, windows/windows_update_install/prepare_msu_file.yml, windows/windows_update_install/windows_update_install.yml
There may be two types of .msu file, SSU and LCU. If SSU is offered, install SSU firstly. LCU is the actual security update. It should be always offered.
=> [Windows] Install SSU firstly in test case windows_update_install

windows/mdag_enable_disable/mdag_enable_disable.yml
From build 26052, MDAG is deprecated. Skip MDAG test from the build.
=> [Windows] Skip MDAG test for build greater than 26052

common/vm_get_guest_info.yml
VM with latest VMware Tools on newer vSphere (looks like 8.0U2) post the detailed data to guest info instead of VM extra config. This fix is to set `guestinfo_detailed_data` with  `vm_guestinfo.instance.guest.guestDetailedData` if it is not empty.
=> Update guestinfo_detailed_data on newer vSphere with latest VMware Tools

autoinstall/FreeBSD/13/installerconfig
Issue:
[FreeBSD 13 32bit] autoinstall is failed due to not to get kde5 package from repo
Result:
+----------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'           |
|                           | bitness='32'                 |
|                           | distroName='FreeBSD'         |
|                           | familyName='FreeBSD'         |
|                           | kernelVersion='13.3-RELEASE' |
+----------------------------------------------------------+
Test Results (Total: 1, Passed: 1, Elapsed Time: 00:45:45)
+-------------------------------------------------------+
| ID | Name                        | Status | Exec Time |
+-------------------------------------------------------+
|  1 | deploy_vm_bios_nvme_vmxnet3 | …
=> [FreeBSD 13 32bit] Fix autoinstall failure due to no kde5 package from quarterly repo

autoinstall/FreeBSD/13/installerconfig, autoinstall/FreeBSD/14/installerconfig
Description:
Remove kde5 for FreeBSD 13&14 32bit
Test result:
1) FreeBSD 13 32bit
2) FreeBSD 13 64bit
3)FreeBSD 14 64bit
4)FreeBSD 14 32bit
=> [FreeBSD 32bit] Remove kde5 for FreeBSD 13&14 32bit

autoinstall/FreeBSD/13/installerconfig, autoinstall/FreeBSD/14/installerconfig
Issue:
install open-vm-tools-nox11 by mistake for freebsd 64bit
Test result:
1) Test result for FreeBSD 14 & 13 32bit:
-----------------------------------------------------------------+
|  1 | deploy_vm_bios_nvme_vmxnet3 |   Passed         | 00:38:36  |
|  2 | ovt_verify_status           | * Not Applicable | 00:00:45  |
+-----------------------------------------------------------------+
2)  Test result for FreeBSD 14 & 13 64bit:
Test Results (Total: 2, Passed: 2, Elapsed Time: 00:38:27)
+------------------------------------------------------+
| ID | Name                       | Status | Exec Time |
+------------------------------------------------------+
|  1 | deploy_vm_efi_nvme_vmxnet3 | Passed | 00:37:14  |
|  2 | ovt_verify_status          | Passed | 00:00:59  | …
=> [FreeBSD]fix: install open-vm-tools-nox11 by mistake for freebsd 64bit

linux/utils/add_official_online_repo.yml, linux/utils/get_rpm_gpg_key_file.yml
Photon OS package installation requires 4096 bit GPG key now, otherwise it will led to package installation failures like below:
```
"module_args": {
"_raw_params": "tdnf install -y cloud-init",
"_uses_shell": false,
"argv": null,
"chdir": null,
"creates": null,
"executable": null,
"removes": null,
"stdin": null,
"stdin_add_newline": true,
"strip_empty_ends": true
}
},
"msg": "non-zero return code",
"rc": 234,
...
"stdout_lines": [
"",
"Installing:",
"lzo                      x86_64       2.10-1.ph4       photon       143.85k 147304",
"python3-pyserial         noarch       3.5-1.ph4        photon       853.34k 873822",
"btrfs-progs              x86_64       5.7-3.ph4        photon         4.88M 5122206",
"",
"Total installed size:   5.86M 6143332",
"",
"Upgrading:", …
```
=> [Linux] Update Photon OS GPG key file to 4096 bit

plugin/ansible_vsphere_gosv_log.py
With latest VMTools, the guest id in guest info for MIRACL LINUX 9.2 is empty string, but in our results.log it is not. By checking log plugin, it erased all empty values. So this fix is to correct that. All facts will take the last value as its final value, no matter it is empty or not.
```
+------------------------------------------------------------------------------------------------------------+
| Config Guest Id           | asianux8_64Guest                                                               |
+------------------------------------------------------------------------------------------------------------+
| GuestInfo Guest Id        |                                                                                |
+-------------------------------------------------------------- …
```
=> Correct guest info guest id in results.log and guest_info.json

common/reset_base_snapshot.yml, linux/setup/create_base_snapshot.yml
**Description:**
Fix the Ping issue for FreeBSD 13&14 32bit and 64bit.
**Test result:**
Testing all the async packages and don't hit the ping issue with the changes:
1) FreeBSD 13 32bit and FreeBSD 13 64bit
2) FreeBSD 14 32bit and FreeBSD 14 64bit
Note:
For the FreeBSD 14 64bit, part of the async packages are without desktop after autoinstall.  I am working on this issue.
=> [FreeBSD] Fix the ping issue for FreeBSD 

autoinstall/FreeBSD/14/installerconfig
**Description**
testcase ovt_verify_status  is failed at detecting vmtoolsd user process
**Root Cause**
It's because the Xserver is failed to bootup which caused by failure to install package xf86-video-vmware at autoinstall.
**Test result**
Passed to rerun all the failure async pacakges
=> [FreeBSD 14] Missing the desktop cause the failure of testcase ovt_verify_status  at detecting vmtoolsd user process

linux/open_vm_tools/uninstall_ovt.yml, linux/setup/reconfig_existing_guest.yml
Two issue:
1) ovt_verify_pkg_install failed due to running /usr/lib/packagekitd on opensuse-15.6-GA-64bit
2) undefined variable is reported in ovt_verify_pkg_install on opensuse-15.6-GA-64bit
Test result:
1) pass the testing for issue 1:
2) The testing is on-going for issue 2
=> [OpenSUSE] ovt_verify_pkg_install is failed and undefined variable is reported in ovt_verify_pkg_install 

README.md, changelogs/changelog.yml
Docker images published for each releases are moved to this path: projects.packages.broadcom.com/gos_cert/ansible-vsphere-gos-validation
=> Change docker images' path

common/esxi_get_version_build.yml
If getting ESXi server properties failed, directly fail the test and print out the error message.
Negative test:
```
TASK [Get ESXi server product info] *************************************************************************************************************************************************************************************************
task path: /home/qiz/workspace/github/ansible-vsphere-gos-validation/common/esxi_get_version_build.yml:10
"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
}
...ignoring
Read vars_file '../../vars/test_esx.yml'
Read vars_file '../../vars/test_esx.yml'
Read vars_file '../../vars/test_esx.yml'
Read vars_file '../../vars/test_esx.yml'
TASK …
```
=> Print error message when failed to get ESXi server config properties

common/vm_check_vmtools_capability.yml, linux/gosv_testcase_list.yml, linux/host_verify_saml_token/check_host_verified_token.yml, linux/host_verify_saml_token/check_tools_capability.yml, linux/host_verify_saml_token/host_verify_saml_token.yml, linux/host_verify_saml_token/test_guest_ops_with_token.yml, linux/utils/collect_vgauth_logs.yml, linux/vgauth_check_service/vgauth_check_service.yml, tools/vgauth_guestops.py, windows/gosv_testcase_list.yml, windows/host_verify_saml_token/host_verify_saml_token.yml, windows/utils/win_collect_vgauth_logs.yml
Add a new test case to test host verified SAML token when performing VGAuth guest operations.
Tested on Windows:
```
+------------------------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                                           |
|                           | bitness='64'                                                 |
|                           | buildNumber='26100'                                          |
|                           | distroName='Windows'                                         |
|                           | distroVersion='10.0'                                         |
|                           | familyName='Windows'                                         |
|                           | …
```
=> Add new test case host_verify_saml_token

linux/setup/reconfig_existing_guest.yml, linux/setup/test_setup.yml, linux/utils/install_uninstall_package.yml
When deploying VM from Photon OS 4.0 OVA, it can't install required packages `python3-rpm` at cloud-init config because the expired 1024 GPG key, which would led to getting installed packages failed or installing packages failed in the VM because of:
```
task path: /home/worker/workspace/Ansible_Regression_Photon_4.0_OVA/ansible-vsphere-gos-validation/linux/utils/get_installed_packages.yml:12
fatal: [localhost -> 10.185.15.85]: FAILED! => {
"module_args": {
"manager": [
"auto"
],
"strategy": "first"
}
},
"msg": "Could not detect a supported package manager from the following list: ['pkg_info', 'apk', 'portage', 'pkg', 'apt', 'pacman', 'rpm'], or the required Python library is not installed. Check warnings for details.",
"warnings": [
"Found \"rpm\" but …
```
=> Force to install latest required packages on Photon OS

README.md, autoinstall/RHEL/8/server_with_GUI/ks.cfg, autoinstall/RHEL/8/server_without_GUI/ks.cfg, linux/guest_customization/check_network_config.yml, linux/guest_customization/linux_gosc_start.yml, linux/guest_customization/linux_gosc_workflow.yml, linux/utils/get_network_config_file.yml, linux/utils/get_rpm_gpg_key_file.yml, linux/vhba_hot_add_remove/vhba_device_hot_add_remove.yml
CentOS Stream 10 ISO has been published, there is RHEL 10 nightly ISO for testing.
Automation testing needs to be well prepared for incoming RHEL 10.0 releases.
Changes in this fix are tested on CentOS Stream 10. Testing on RHEL 10 nightly are on-going. Unattended config file will keep using kickstart files under autoinstall/RHEL/8 with some compatible changes. `pwpolicy` was deprecated in RHEL 9.0, and removing it won't affect our automation testing, so this fix directly removed them.
In CentOS Stream 10, network connections are completely managed by NetworkManager, there is no /etc/sysconfig/network-scripts/ directory any more. So GOSC test cases also updated to collect network config files.
`check_inbox_driver` failed due to missing `vmw_vmci`, `vmw_vsock_vmci_transport` and …
=> [Linux] Add support for RHEL 10 and CentOS 10

linux/vhba_hot_add_remove/vhba_device_hot_add_remove.yml
Since RHCOS 4.16.0, LSILogic and LSILogicSAS  controllers are not supported. Skip the two vHBA test cases.
=> [Linux] Skip LSILogic and LSILogicSAS testing for RHCOS 4.16.0 or later

linux/utils/check_guest_os_gui.yml
Xorg server has been deprecated in latest RHEL and Ubuntu releases, which has been replaced by Wayland. 
In our tests, checking Xorg installed or not is not precise for determine whether the guest OS has GUI. For example, the guest OS may install Xorg but has no desktop environment. 
For FreeBSD system, the display manager may relies on Xorg or Xwayland. So if there is running process of Xorg or Xwayland, it means the OS has desktop environment. 
For Linux system, we can also check running process of Xorg or Xwayland, but Linux guest OS coverage is more than FreeBSD, the same command couldn't work on all Linux system. As we also need to get Linux system display manager, so this fix directly check whether display-manager is running. If it is running, that means the OS has desktop …
=> [Linux] Check guest has GUI from display-manager service or running Xorg or Xwayland process

autoinstall/SLE/15/SP3/SLES/autoinst.xml, autoinstall/SLE/15/SP4/SLED/autoinst.xml, autoinstall/openSUSE/15/autoinst.xml
- Update autoinst.xml without separate /home partition for SLE and openSUSE
- Per https://documentation.suse.com/sles/15-SP3/single-html/SLES-autoyast/index.html: One partition can have the value max to use all remaining space. 
- Autoinstall and testing passed with sles-15.3/15.6, sled-15.6 and opensuse-15.6
```
NAME="SLES"
VERSION="15-SP6"
VERSION_ID="15.6"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP6"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp6"
DOCUMENTATION_URL="https://documentation.suse.com/"
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        78G  4.6G   72G   7% /
devtmpfs        4.0M     0  4.0M   0% /dev
tmpfs           1.8G     0  1.8G   0% /dev/shm
efivarfs        256K   55K  197K  22% /sys/firmware/efi/efivars
tmpfs …
```
=> update autoinst.xml without separate /home partition for opensuse/sle-15.6

autoinstall/SLE/15/SP3/SLED/autoinst.xml, autoinstall/SLE/15/SP3/SLES/autoinst.xml, autoinstall/SLE/15/SP3/SLES_Minimal/autoinst.xml, autoinstall/SLE/15/SP4/SLED/autoinst.xml, autoinstall/openSUSE/15/autoinst.xml, linux/setup/reconfig_existing_guest.yml
Issue:
ovt_verify_pkg_install failed due to running /usr/lib/packagekitd on opensuse-15.6-GA-64bit
Test result:
1) Passed this testcases for 4 times trying
2) The status of packagekit.service is expected when check VM
3) Note:
systemctl disable packagekit.service
disable makes the unit disabled during boot. But that unit can be started anytime after boot. 
systemctl mask packagekit.service
mask disables the unit completely. It can't be started without unmasking. That automatically implies it will fail during boot.
=> [Linux] Mask packagekit service for Suse family OS

linux/open_vm_tools/install_ovt_from_source.yml, linux/open_vm_tools/pre_ovt_install.yml, linux/open_vm_tools/templates/linux_ovt_build_config.tmpl, linux/utils/add_local_dvd_repo.yml, linux/utils/add_official_online_repo.yml
This fix is to enable ovt_verify_src_install for Suse family OS, including SLED, SLES and openSUSE.
Regression tests passed with SLED 15 SP6, SLES 15 SP6, openSUSE Leap 15.6, Debian 10&11&12, Pardus 21&23, Ubuntu 20.04&22.04&23.04.
=> [Linux] Support to test installing open-vm-tools from source on Suse family OS

linux/network_device_ops/pvrdma_client_network_device_ops.yml, linux/network_device_ops/pvrdma_network_device_ops.yml, linux/network_device_ops/refresh_pvrdma_client_vm_ip.yml, linux/network_device_ops/start_pvrdma_server.yml
The VM guest IP might be changed after hot adding a new adapter and apply new netplan config on Ubuntu.
This fix updated the server VM and client VM guest IP after hot adding new adapter. And added retries to start PVRDMA server rping listening.
```
+-------------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                                |
|                           | bitness='64'                                      |
|                           | distroAddlVersion='22.04.4 LTS (Jammy Jellyfish)' |
|                           | distroName='Ubuntu'                               |
|                           | distroVersion='22.04'                             |
|                           | familyName='Linux' …
```
=> [Linux] Fix PVRDMA failure due to server VM or client VM IP changed for Ubuntu

changelogs/changelog.yml, env_setup/env_setup.yml, linux/deploy_vm/delete_unattend_install_iso.yml, linux/deploy_vm/deploy_vm.yml, linux/network_device_ops/hot_remove_network_adapter.yml, linux/secureboot_enable_disable/check_secureboot_support_status.yml, linux/utils/enable_vgauth_logging.yml, linux/utils/enable_vmtools_logging.yml, linux/vhba_hot_add_remove/wait_device_list_changed.yml, windows/check_os_fullname/check_os_fullname.yml, windows/cpu_hot_add_basic/cpu_hot_add_basic.yml, windows/guest_customization/handle_guest_known_issues.yml, windows/guest_os_inplace_upgrade/handle_known_issue.yml, windows/memory_hot_add_basic/memory_hot_add_basic.yml, windows/utils/win_enable_vgauth_log.yml, windows/vbs_enable_disable/vbs_enable_disable.yml, windows/vbs_enable_disable/vbs_enable_test.yml
VMware KB links are redirected to Broadcom KB links now. This change is to use the Broadcom KB links.
GOSC related KB links were updated in https://github.com/vmware/ansible-vsphere-gos-validation/pull/608.
=> Replace VMware KB links with Broadcom KB links

linux/setup/test_setup.yml, linux/utils/enable_disable_cloudinit_cfg.yml, linux/utils/install_uninstall_package.yml
Stop and enable services might cause failures on Ubuntu OS. This fix is to separate service operations for enabling cloud-init GOSC. Firstly, stop cloud-init services, then modify cloud-init configs, and after that enable cloud-init services.
=> [Linux] Enable cloud-init services after modifying configs for cloud-init GOSC

linux/utils/enable_disable_cloudinit_cfg.yml, linux/utils/get_cloudinit_version.yml
The cloud-init version get from Ansible package module is not a full version on RHEL family. This change directly gets the cloud-init version from cloud-init command
Take RHEL_9.4 as an example, before this change, cloud-init version get from Ansible module is 23.4; with this change, we can get the full version 23.4-7.el9_4.
```
Photon_5.0: 24.2
RHEL_9.x: 23.4-7.el9_4
RHEL_7.x: 19.4
RockyLinux_8.x: 23.4-7.el8_10.0.1
ProLinux_8.x: 21.1-15.0.1.el8
CentOS_10: 24.1.4-13.el10
Debian_10.x_64: 20.2
Photon_4.0: 24.2
Ubuntu_24.04: 24.1.3-0ubuntu3
Pardus_23.x: 22.4.2
```
=> [Linux] Get cloud-init version from command line

linux/open_vm_tools/install_ovt_from_source.yml, linux/open_vm_tools/templates/linux_ovt_build_config.tmpl, linux/open_vm_tools/templates/linux_ovt_check_config.tmpl, linux/utils/get_cloudinit_version.yml, linux/utils/get_os_edition.yml
1. Ubuntu 24.04 has upgraded gtk and gtkmm version, which would led to MKS related function issue. This fix is to skip compiling about X plugins on Ubuntu 24.04. 
2. Ubuntu 24.04 desktop installed ubuntu-desktop-minimal not ubuntu-desktop. So I also updated the edition check by searching for packages like ubuntu-server or ubuntu-desktop.
3. When cloud-init is not installed, command `/usr/bin/cloud-init --version 2>&1` failed, but with the pipe ` | awk '{print $2}', its rc is 0. So this fix also checked the cloud-init binary exists or not before getting cloud-init version.
```
+--------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                           |
|                           | bitness='64' …
```
=> [Linux] Add config option 'without-x' for installing open-vm-tools from source on Ubuntu 24.04

common/vm_get_vm_info.yml
When the datastore name has space like `datastore2 (1)`, the value of datastore set in `common/vm_get_vm_info.yml` remove the space and characters following it, like `datastore2`.
This fix is to correct VM's datastore value.
Datastore name has space
```
TASK [Display VM's basic information] ************************************************************************************************************************************************************************************************
task path: /home/qiz/workspace/github/ansible-vsphere-gos-validation/common/vm_get_vm_info.yml:28
"msg": [
"VM datastore: datastore2 (1)",
"VM files path: /vmfs/volumes/datastore2 (1)/LinuxMint-22-Xfce-EFI-Tools-HW20/",
"VM files path: [datastore2 (1)] LinuxMint-22-Xfce-EFI-Tools-HW20/",
"VM …
```
=> Fix VM datastore value when the datastore name has space

windows/windows_update_install/prepare_msu_file.yml
For OS older than 17763 (Windows 1809 or Windows Server 2019), it has very high frequency of timeout for the command.
Hence for these older OS, hard code the drive letter to mount the shared folder.
=> [Windows] set fixed mount point for older OS versions in test case windows_update_install

windows/utils/win_install_online_updates.yml
When installing the windows online updates, the returned result may not contain the attribute "failure_msg" for the not installed updates.
=> [Windows] fix the undefined error when checking the failure_msg for windows online update installation

linux/utils/enable_disable_cloudinit_cfg.yml
The cloud-init services are changed from version 24.3. Ubuntu 24.10 Beta has cloud-init 24.4, this fix is to resolve failed cloud-init GOSC testing on Ubuntu 24.10.
=> [Linux] Update cloud-init services for version 24.3 or later

linux/power_operation_scripts/power_operation_scripts.yml, linux/power_operation_scripts/set_power_script.yml
Problem
-------------
power_operation_scripts hit intermittent failure for many guestOS such as Ubuntu and rhcos.
Root Cause:
-------------
Need to wait several seconds for wait configuration sync after modify etc/vmware-tools/tools.conf 
Test result:
Passed for Ubuntu 24.04 Live Server  and  Desktop, RHCOS.
=> [Linux] Fix power_operation_scripts failures

linux/utils/add_local_dvd_repo.yml
Ansible mount module will write an entry to /etc/fstab when state=mounted. See https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html
And when state=absent, the entry should be removed from /etc/fstsab, but it seems not working all the time. This fix is to change state=ephemeral for mounting CDROM, so that it won't write the mount entry to /etc/fstab. So that after a reboot, it will not break the system due to not finding the fstab entry device.
=> [Linux] Mount CDROM device with state=ephemeral for adding local DVD repo

autoinstall/Fedora/36/Workstation/ks.cfg
- Update gdm setting for Fedora to resolve the issue of black screen after autoinstall: only Fedora 38, 39 and 40 need to start with the workaround WaylandEnable=false. Fedora 36, 37 and 41 can start with default setting.
- Internal testing passed for all these releases.
=> Update gdm setting for Fedora

linux/open_vm_tools/add_enable_service.yml, linux/open_vm_tools/templates/vmware-guestd.tmpl, linux/power_operation_scripts/set_power_script.yml, linux/utils/enable_vmtools_logging.yml
Problem:
power_operation_scripts failed on FreeBSD 13.x and 14.x with OVT installed from source
Resolution:
1. FreeBSD VM has OVT packages installed, and then it will uninstall original OVT packages and install with OVT from source. In such scenario, our case will firstly download the original vmtools service file before uninstalling the OVT packages, and then reuse them after OVT source install. Then the original vmtools file should be updated with /etc/vmware-tools/tools.conf before using it. You may update it at https://github.com/vmware/ansible-vsphere-gos-validation/blob/main/linux/open_vm_tools/add_enable_service.yml#L63
2. FreeBSD VM doesn't have OVT packages installed, and then it will install OVT from source. In such scenario, our case will create the vmtools service file from a …
=> [FreeBSD]power_operation_scripts failed on FreeBSD 13.x and 14.x with OVT installed from source

linux/open_vm_tools/pre_ovt_install.yml, plugin/ansible_vsphere_gosv_log.py
If test failed at env_setup, deploy_vm, or installing tools, set the following test cases results to Blocked.
Failed at env_setup:
```
Test Results (Total: 32, Blocked: 32, Elapsed Time: 00:00:03)
+-------------------------------------------------------------------+
| ID | Name                                 |   Status  | Exec Time |
+-------------------------------------------------------------------+
| 01 | deploy_vm                            | * Blocked | 00:00:00  |
| 02 | ovt_verify_pkg_install               | * Blocked | 00:00:00  |
| 03 | ovt_verify_src_install               | * Blocked | 00:00:00  |
| 04 | ovt_verify_status                    | * Blocked | 00:00:00  |
| 05 | vgauth_check_service                 | * Blocked | 00:00:00  |
| 06 | host_verify_saml_token …
```
=> [Plugin] Set test case to Blocked when env setup and installing tools failed

common/get_guest_system_info.yml, linux/setup/reconfig_existing_guest.yml
python3-rpm is required by guest OS with Python3 as default python interpreter. This fix added a checking about python version.
```
+------------------------------------------------------------------------------------------+
| Product | Version | Build    | Hostname or IP | Server Model                             |
+------------------------------------------------------------------------------------------+
| vCenter | 7.0.3   | 22357613 |                |                                          |
+------------------------------------------------------------------------------------------+
| ESXi    | 7.0.3   | 22348816 |                | VMware, Inc. VMware20,1                  |
|         |         |          |                | Intel(R) Xeon(R) Gold 6330 CPU @ …
```
=> [Linux] Check python version to install python3-rpm package

windows/host_verify_saml_token/host_verify_saml_token.yml
The host_verify_saml_token failed due to expired saml token. This fix enabled timesync with ESXi host server in Windows guest OS.
```
+-------------------------------------------------------------------------------------------+
| Name                      | test_vm                                                       |
+-------------------------------------------------------------------------------------------+
| Guest OS Distribution     | Microsoft Windows 10 Enterprise 10.0.19045.0 64-bit           |
+-------------------------------------------------------------------------------------------+
| Hardware Version          | vmx-22                                                        |
+------------------------------------------------------------------------------------- …
```
=> [Windows] Enable timesync with ESXi host before verifying SAML token

linux/utils/enable_disable_cloudinit_cfg.yml
cloud-init-network.service and cloud-init-main.service were not found on Photon OS and Ubuntu with cloud-init 24.3.1 installed. So getting cloud-init services list is not accurate by cloud-init version. This fix will directly search for cloud-init services in ansible distribution services fact.
```
TASK [Get all cloud-init services on Ubuntu 22.04 Desktop x86_64] ************************************************************************************************
task path: /home/qiz/workspace/ansible-vsphere-gos-validation/linux/utils/enable_disable_cloudinit_cfg.yml:49
"cloud_init_services": [
"cloud-init-local.service",
"cloud-config.service",
"cloud-final.service",
"cloud-init-hotplugd.service",
"cloud-init.service"
]
},
}
....
VM …
```
=> [Linux] Get cloud-init services list by searching services fact

common/esxi_enable_guest_ip_hack.yml
Replace esxcli command with Ansible module to enable guest IP hack on ESXi host.
```
TASK [Display current state of guest IP hack on ESXi host] *******************************************************************************************************
task path: /home/qiz/workspace/ansible-vsphere-gos-validation/common/esxi_enable_guest_ip_hack.yml:7
"msg": "Current value of 'Net.GuestIPHack' is 0"
}
TASK [Enable GuestIPHack on ESXi host '192.168.1.2'] *****************************************************************************************
task path: /home/qiz/workspace/ansible-vsphere-gos-validation/common/esxi_enable_guest_ip_hack.yml:19
included: /home/qiz/workspace/ansible-vsphere-gos-validation/tests/unit_tests/../../common/esxi_set_advanced_system_settings.yml for …
```
=> Enable guest IP hack with vmware_host_config_manager module

plugin/ansible_vsphere_gosv_log.py
If test failed before setting deploy_vm test case name, changes in this fix will update the test case name as possible as the plugin can.
=> Update deploy_vm test case full name in log plugin

linux/deploy_vm/templates/post_install_scripts/freebsd_post_config.sh
This is to work around core dump issue of 32bit FreeBSD VM on Intel Sapphire Rapids CPU based on FreeBSD's solution:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=283276#c1
=> Increase kern.kstack_pages for 32bit FreeBSD

linux/check_os_fullname/check_os_fullname.yml, linux/check_os_fullname/check_unmapped_guest_id.yml, linux/check_os_fullname/get_other_linux_guest_ids.yml, linux/check_os_fullname/map_guest_id_to_fullname.yml, linux/check_os_fullname/match_guest_id.yml, linux/check_os_fullname/validate_os_fullname.yml, linux/setup/test_setup.yml
VM's guest info relies on ESXi version, VMware Tools version and VM hardware version. This fix added VMware Tools version checking for guest OS identified by newer VMware Tools, and added guest info checking for all compatible hardware versions.
=> [Linux] Check VM guest info with compatible hardware versions and VMware Tools

linux/guest_customization/linux_gosc_execution.yml, linux/guest_customization/linux_gosc_workflow.yml, windows/guest_customization/win_gosc_execution.yml
When GOSC failed, the VM power state is powered off. In such state, we can't collect any logs from guest OS. Here added power state checking before collecting logs. 
This fix also added an assertion task to print GOSC failure message like:
```
TASK [Check the Linux guest OS is customized] *******************************************************************************************************************************************************************************************************************************************
task path: /home/qiz/workspace/ansible-vsphere-gos-validation/linux/guest_customization/linux_gosc_execution.yml:41
"assertion": "not customize_linux_result.failed",
"msg": "Guest customization …
```
=> Add assertion for checking GOSC result and check VM power state before collecting Linux GOSC logs

linux/utils/get_device_list.yml
Before hot adding a SATA disk on FreeBSD, its disk list is as below:
```
$ lsblk -d | grep -v SIZE | grep -v cd0
da0     40G VMware Virtual disk
-        0G TOTAL SYSTEM STORAGE
```
After hot adding a SATA disk, its disk list is as below:
```
$ lsblk -d | grep -v SIZE | grep -v cd0
ada0   1.0G VMware Virtual SATA Hard Drive
da0     40G VMware Virtual disk
-       41G TOTAL SYSTEM STORAGE
```
The value of TOTAL SYSTEM STORAGE changed, therefore we got two different items after hot adding SATA disk, which led to test failed.
This fix will only list disks without the line of 'TOTAL SYSTEM STORAGE' , so that we can only compare the changed devices list.
```
"guest_disk_list_before_hotadd": [
{
"model": "VMware Virtual disk",
"name": "da0",
"size": "40G"
}
]
...
"guest_disk_list_after_hotadd": …
```
=> [FreeBSD] Get rid of TOTAL SYSTEM STORAGE in output of listing disks

common/README.md, common/test_ssh_connection.yml, common/vcenter_manage_domain_user.yml, linux/host_verify_saml_token/host_verify_saml_token.yml, windows/host_verify_saml_token/host_verify_saml_token.yml
Added a task file to test SSH connection before starting host_verify_saml_token test. If SSH connection failed, test case is blocked.
Added ignore_unreachable for vCenter Server shell command so that unreachable error won't block the following test cases.
SSH success:
```
+-----------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                        |
|                           | bitness='64'                              |
|                           | cpeString='cpe:/o:prolinux:prolinux:8.6'  |
|                           | distroAddlVersion='8.6'                   |
|                           | distroName='ProLinux'                     |
|                           | distroVersion='8.6'                       |
| …
```
=> Ignore unreachable error for vCenter Server SSH connection

linux/utils/add_official_online_repo.yml, linux/utils/disable_repo.yml, linux/utils/install_uninstall_package.yml
Removed ProLinux online repos and changed to install packages from ProLinux ISO only.
```
TASK [Install latest packages on ProLinux 8.6] ***************************************************************************************************************************************************************************************************************************************
task path: /home/qiz/workspace/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:153
changed: [localhost -> ] => {
"changed": true,
"cmd": "dnf install -y python3-rpm",
"delta": "0:00:06.324375",
"end": "2025-02-07 00:58:10.186537",
"module_args": {
"_raw_params": "dnf install -y python3-rpm",
"_uses_shell": true,
"argv": null,
"chdir": null,
"creates": null,
"executable": null, …
```
=> [Linux] Disable ProLinux online repos because they are not reachable

plugin/ansible_vsphere_gosv_log.py
This change is to print reason in error message.
Some failed task result only has 'reason' as below, which led to error message is empty
```
2025-02-13 11:40:22,013 | TASK [localhost][Get SSH public key from localhost] ********
task path: /home/qiz/workspace/ansible-vsphere-gos-validation/tests/unit_tests/test_rebuild_iso.yml:27
"reason": "Could not find or access '/home/qiz/workspace/ansible-vsphere-gos-validation/tests/utils/get_local_ssh_public_key.yml' on the Ansible Controller."
}
error message:
```
With this change, we can extract error message as:
```
error message:
Could not find or access '/home/qiz/workspace/ansible-vsphere-gos-validation/tests/utils/get_local_ssh_public_key.yml' on the Ansible Controller.
```
Some failed task result has both of …
=> [Plugin] Add task reason to extracted error message

README.md, linux/network_device_ops/hot_add_network_adapter.yml, linux/open_vm_tools/check_inbox_drivers_unchanged.yml, linux/open_vm_tools/check_ovt_plugins_loaded.yml, linux/open_vm_tools/install_ovt_from_package.yml, linux/open_vm_tools/install_ovt_from_source.yml, linux/open_vm_tools/templates/linux_ovt_build_config.tmpl, linux/setup/reconfig_existing_guest.yml, linux/utils/collect_dmesg.yml, linux/utils/disable_firewall.yml, linux/utils/get_file_real_path.yml, linux/vhba_hot_add_remove/hot_add_remove_disk.yml, linux/vhba_hot_add_remove/vhba_device_hot_add_remove.yml
Changes in this fix is to support run testing on an existing SLES 16 SP0 VM.
1. Fixed open-vm-tools source install dependencies
2. Fixed inbox drivers checking after installing open-vm-tools from source
3. Fixed open-vm-tools plugins paths after installing open-vm-tools from source
4. Added workaround for disabled vmtoolsd and vgauthd after reinstalling open-vm-tools packages
5. Installed dependency 'python311-rpm' before testing starts.
6. Added firewall service checking before stopping and disabling it.
7. Added dmesg collection after hot adding or removing a hard disk.
Test results:
```
+------------------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                                     |
| …
```
=> [Linux] Support SLES 16 automation testing on existing VM

linux/power_operation_scripts/set_power_script.yml, windows/power_operation_scripts/set_power_script.yml
ansible.builtin.include has been removed and use include_tasks instead for testcase power_operation_scripts
Test passed:
=> Replace "include" with "include_tasks" in testcase power_operation_scripts

linux/deploy_vm/templates/post_install_scripts/freebsd_post_config.sh, linux/deploy_vm/wait_autoinstall_complete.yml, linux/open_vm_tools/install_ovt_from_source.yml, linux/utils/freebsd_update_fstab_with_uuid.yml
The KDE desktop fails to display correctly after the automatic installation of FreeBSD 13.5 64-bit. This issue arises because the sddm package, which was included in the ISO, was installed, but the kde5 package was not available on the ISO and had to be installed from the online repository. Additionally, several other dependent packages had version mismatches between the ISO and the online repository. These version differences caused the sddm greeter to fail, preventing the desktop from working properly.
Upon reviewing the FreeBSD 13.5 and 14.2 ISOs, it appears both contain GNOME and the gdm package. This means GNOME and gdm can be directly installed from the ISO, which may help avoid compatibility issues with package versions. Since the contents of FreeBSD ISOs can change between …
=> [FreeBSD] Use GNOME as FreeBSD 64bit desktop environment

linux/deploy_vm/templates/post_install_scripts/freebsd_post_config.sh, linux/open_vm_tools/ovt_verify_status.yml, linux/utils/check_guest_os_gui.yml, linux/utils/enable_auto_login.yml
Enabling auto login in gdm will cause FreeBSD black screen. This fix added slim as the display manager in FreeBSD, and enabled auto login by using slim.
```
- 'Guest os distribution: Ubuntu 20.04 Server x86_64'
- 'Results: Total (2), Passed (2)'
- ' * deploy_vm_efi_paravirtual_vmxnet3...............................Passed'
- ' * ovt_verify_status...............................................Passed'
- 'Guest os distribution: Pardus GNU/Linux 21.5 XFCE x86_64'
- 'Results: Total (2), Passed (2)'
- ' * deploy_vm_efi_paravirtual_vmxnet3...............................Passed'
- ' * ovt_verify_status...............................................Passed'
- 'Guest os distribution: CentOS 10 x86_64'
- 'Results: Total (2), Passed (2)'
- ' * deploy_vm_efi_paravirtual_vmxnet3............................ …
```
=> [FreeBSD] Enable auto login in slim for FreeBSD GNOME

linux/host_verify_saml_token/host_verify_saml_token.yml, windows/host_verify_saml_token/host_verify_saml_token.yml
Test ssh connection only when ESXi, VMTools and guest OS support this test case
```
+------------------------------------------------------------------------------------------------+
| Product | Version | Build    | Hostname or IP                   | Server Model                                               |
+------------------------------------------------------------------------------------------------+
| vCenter | 8.0.0   | 20519528 |                                  |                                                       |
+------------------------------------------------------------------------------------------------+
| ESXi    | 8.0.0   | 21493926 |                                  | Dell Inc. PowerEdge R6525                                  |
|         | …
```
=> Test ssh connection after ESXi, VMTools and guest compatibilty check

linux/deploy_vm/deploy_vm_from_iso.yml
Debian 11.11 GNOME desktop couldn't display because the video memory is too small. Increase Debian VM's video memory to 8 MB to fix it.
=> [Linux] Increase Debian VM's video memory to 8 MB

common/ovf_deploy.yml, vars/test.yml
Update ovf_deploy.yml to reconfigure vCPU and memory settings when memory_mb, cpu_number, and cpu_cores_per_socket are specified and differ from the default configuration of the VM deployed from the OVF. This enhancement will improve performance and ensure a smoother experience when running desktop applications on it by allocating additional CPU and memory resources.
Testing done:
```
TASK [Set the facts of vm memory and initial configuration] ********************
task path: /home/worker/workspace/Ansible_Cycle_Photon_5.x_Update_OVA-42/ansible-vsphere-gos-validation/common/ovf_deploy.yml:28
"initial_mem_mb": "4096",
"vm_mem_mb": "1024"
},
}
......
TASK [Check VM memory size after setting] **************************************
task …
```
=> Update ovf_deploy.yml to reconfigure vcpu and memory

autoinstall/Ubuntu/Server/user-data.j2
Ubuntu 25.04 Server autoinstall crashes due to failed to install package ndctl ..
Jira Task: GOSV-4514
=> [Linux] Fix Ubuntu 25.04 Server autoinstall crashes when installing ndctl and rdma packages

linux/network_device_ops/prepare_network_device_test.yml
If VM has a serial port, VM instant clone will fail. This fix is to remove serial ports before PVRDMA testing, in which VM will be instant cloned.
Below test was run by keeping the serial port after VM deployment.
```
+------------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                               |
|                           | bitness='64'                                     |
|                           | cpeString='cpe:/o:suse:sles:15:sp7'              |
|                           | distroAddlVersion='15-SP7'                       |
|                           | distroName='SLES'                                |
|                           | distroVersion='15.7'                             |
| …
```
=> [Linux] Remove serial port before PVRDMA testing

linux/open_vm_tools/templates/linux_ovt_build_config.tmpl
`libdnet-devel` was removed from SLES 16 Snapshot-202504-1, but `libvmtools-devel` is required in SLES 16 now.
```
+------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                         |
|                           | bitness='64'                               |
|                           | cpeString='cpe:/o:suse:sles:16:16.0'       |
|                           | distroAddlVersion='16.0 Snapshot-202504-1' |
|                           | distroName='SUSE Linux'                    |
|                           | distroVersion='16.0'                       |
|                           | familyName='Linux'                         |
|                           | kernelVersion='6.12.0-160000.9-default'    |
| …
```
=> [Linux] Update dependencies for SLES 16 OVT source install

linux/open_vm_tools/uninstall_ovt.yml, linux/utils/enable_auto_login.yml
openSUSE 16.0 Beta release doesn't have open-vm-tools-desktop installed as it has no desktop. To avoid uninstalling non-existing package, this fix filtered out installed open-vm-tools packages, and then uninstall them.
```
+---------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                      |
|                           | bitness='64'                            |
|                           | cpeString='cpe:/o:opensuse:leap:16.0'   |
|                           | distroAddlVersion='16.0 Beta'           |
|                           | distroName='openSUSE Leap'              |
|                           | distroVersion='16.0'                    |
|                           | familyName='Linux'                      | …
```
=> [Linux] Get installed open-vm-tools packages before uninstalling

linux/guest_customization/check_gosc_support_status.yml
Task:
GOSV-4718: Change GOSC with cloud-init of pardus 21.x/23.x to unsupportted status
Test result:
Done. please check GOSV-4718
=> [Pardus] Change GOSC with cloud-init of pardus 21.x/23.x to unsupportted status

linux/deploy_vm/deploy_vm_from_ova.yml
When ova_path=/mnt/fedora-42-GA-64bit/fedora-42-GA-64bit.ovf instead of the official ova from ubuntu, photon, rhcos or flatcar, deploy_vm_from_ova failed due to "vm_guest_ip is undefined". 
Fixed this issue and testing done:
```
+--------------------------------------------------------------------------------+
| Hardware Version          | vmx-20                                             |
+--------------------------------------------------------------------------------+
| VMTools Version           | 12.4.0 (build-23259341)                            |
+--------------------------------------------------------------------------------+
| Config Guest Id           | other4xLinux64Guest                                |
+------------------------------------------------------------------------ …
```
=> Fix the conditions for ova deployment

linux/guest_customization/check_gosc_support_status.yml
Skip GOSC testing for scale out guest ids which don't support guest customization.
```
| VMTools Version           | 11.0.5 (build-15389592)                |
+--------------------------------------------------------------------+
| Config Guest Id           | prolinux_64Guest                       |
+--------------------------------------------------------------------+
| GuestInfo Guest Id        | other3xLinux64Guest                    |
+--------------------------------------------------------------------+
| GuestInfo Guest Full Name | Other 3.x Linux (64-bit)               |
+--------------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                             |
+--------------------------------------------------------------------+
| …
```
=> [Linux] Skip GOSC testing for scale out guest ids

linux/utils/get_cpu_info.yml
Due to Ansible module issue https://github.com/ansible/ansible/issues/78092, CPU information is not correct in ansible facts when the VM is running on ARM server. This fix used `lscpu` command to get CPU numbers and cores per socket in guest OS.
```
+-----------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='Arm'                  |
|                           | bitness='64'                        |
|                           | distroAddlVersion='5.0'             |
|                           | distroName='VMware Photon OS'       |
|                           | distroVersion='5.0'                 |
|                           | familyName='Linux'                  |
|                           | kernelVersion='6.1.10-10.ph5-esx'   |
| …
```
=> [Linux] Fix guest OS CPU number and cores per socket for ARM

linux/host_verify_saml_token/set_vsphere_ntp_servers.yml
`ntpClient` firewall rule is owned by system service `ntpd`. It cannot be enabled when `ntpd` service is not running.
=> Enable ntpClient firewall rule after starting ntpd service

linux/utils/add_local_dvd_repo.yml, linux/utils/config_repos.yml, linux/utils/list_repos.yml
Update the local DVD repository name and disable the unavailable online repo for Kylin.
Testing done:
```
+----------------------------------------------------------------------+
| Name                      | cycle_kylinserver_10.1                   |
+----------------------------------------------------------------------+
| Guest OS Distribution     | Kylin Linux Advanced Server 10 x86_64    |
+----------------------------------------------------------------------+
| GUI Installed             | True                                     |
+----------------------------------------------------------------------+
| CloudInit Version         |                                          |
+----------------------------------------------------------------------+
| Hardware Version …
```
=> Update the local and online repos for Kylin Linux

autoinstall/Kylin/Server/10/ks.cfg, linux/utils/config_repos.yml, linux/utils/list_repos.yml
Fixed the following issues for Kylin Linux Server:
1. Invalid value auto for ----reserve-mb" in autoinstall
2. Keep the default online repo for Kylin
Testing done:
```
+-----------------------------------------------------------------------------+
| Guest OS Distribution     | Kylin Linux Advanced Server 10 x86_64           |
+-----------------------------------------------------------------------------+
| GUI Installed             | True                                            |
+-----------------------------------------------------------------------------+
| Hardware Version          | vmx-22                                          |
+-----------------------------------------------------------------------------+
| VMTools Version           | 11.2.5 (build-17337674) …
```
=> [Linux] Fix autoinstall and repo for Kylin Linux

linux/vhba_hot_add_remove/handle_lsilogicsas_known_issue.yml
Test case lsilogicsas_vhba_device_ops failed occasionally because the guest OS cannot recognize the new disk hot added to an existing lsilogicsas controller. It is a Linux kernel issue like Ubuntu. This fix is to mark it as known issue on SLES 16.0 or later and reboot the guest OS to recognize the disk as a workaround.
=> [Linux] Add LSILogicSAS known issue and workaround for SLES 16

linux/vhba_hot_add_remove/vhba_device_hot_add_remove.yml
Check the disk controller is in guest ID supported disk controller list before testing. If it is not supported, skip the test case.
=> [Linux] Skip testing new disk controller type when it is not supported by the guest id

linux/vhba_hot_add_remove/vhba_device_hot_add_remove.yml
If vhba test case is the first test case, guest_config_options is undefined before test setup. This fix is to check new_disk_ctrl_type is supported or not after test setup
=> [Linux] Check disk controller type is supported after test setup

linux/utils/enable_disable_cloudinit_cfg.yml
SLES 16 cloud-init has two empty service files: cloud-init-main.service and cloud-init-network.service. These two services cannot be enabled and started because they don't have `ExecStart` or `ExecStop` settings in their service files.
This fix is to filter out and enable cloud-init services with valid service settings only before cloud-init GOSC.
```
+----------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                             |
|                           | bitness='64'                                   |
|                           | cpeString='cpe:/o:suse:sles:16:16.0'           |
|                           | distroAddlVersion='16.0 Snapshot-202506-1'     |
|                           | distroName='SLES' …
```
=> [Linux] Skip to enable cloud-init services with bad settings for cloud-init GOSC

linux/open_vm_tools/install_ovt_from_source.yml, linux/open_vm_tools/templates/freebsd_ovt_build_config.tmpl
If FreeBSD has fuse2 and fuse3 at the same time, open-vm-tools source configure will fail due to incorrect fuse header file
```
cc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"13.1.0\" -DPACKAGE_STRING=\"open-vm-tools\ 13.1.0\" -DPACKAGE_BUGREPORT=\"[open-vm-tools-devel@lists.sourceforge.net](mailto:open-vm-tools-devel@lists.sourceforge.net)\" -DPACKAGE_URL=\"\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_TIME_H=1 -DSTDC_HEADERS=1 -DPACKAGE=\"open-vm-tools\" -DVERSION=\"13.1.0\" -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_FUSE3=1 -DFUSE_USE_VERSION=35 -DHAVE_X11_SM_SMLIB_H=1 -DHAVE_X11_ICE_ICELIB_H=1 …
```
=> [FreeBSD] Add configure option about fuse for installing open-vm-tools from source

linux/utils/add_official_apt_sources.yml
Debian 10 APT sources are archived. This fix added Debian APT sources checking before using it.
```
TASK [Set fact of available APT sources for Debian buster] *********************
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit-263/ansible-vsphere-gos-validation/linux/utils/add_official_apt_sources.yml:37
"debian_apt_sources": [
"https://archive.debian.org/debian-archive/debian"
]
},
}
TASK [Set fact of official APT sources on Debian 10.13 x86_64] *****************
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit-263/ansible-vsphere-gos-validation/linux/utils/add_official_apt_sources.yml:44
"apt_sources": [
"deb …
```
=> [Linux] Update APT sources for archived Debian release

linux/open_vm_tools/templates/suse_ovt_build_config.tmpl
The doxygen package has been removed from SLES 16 PublicRC. It is not a must-have package for building open-vm-tools source. So here removes it from OVT build dependencies.
```
+----------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                             |
|                           | bitness='64'                                   |
|                           | cpeString='cpe:/o:suse:sles:16:16.0'           |
|                           | distroAddlVersion='16.0 PublicRC'              |
|                           | distroName='SLES'                              |
|                           | distroVersion='16.0'                           |
|                           | familyName='Linux' …
```
=> [Linux] Remove doxygen from open-vm-tools build denepencies on SLES 16

linux/utils/add_official_apt_sources.yml
```
TASK [Install packages ['open-vm-tools', 'open-vm-tools-desktop']] *************
...
"module_args": {
"_raw_params": "apt-get install -y open-vm-tools open-vm-tools-desktop",
"_uses_shell": false,
"argv": null,
"chdir": null,
"creates": null,
"executable": null,
"removes": null,
"stdin": null,
"stdin_add_newline": true,
"strip_empty_ends": true
}
},
"msg": "",
"rc": 0,
"start": "2025-08-13 07:35:48.526184",
"stderr": "debconf: unable to initialize frontend: Dialog\ndebconf: (TERM is not set, so the dialog frontend is not usable.)\ndebconf: falling back to frontend: Readline",
"stderr_lines": [
"debconf: unable to initialize frontend: Dialog",
"debconf: (TERM is not set, so the dialog frontend is not usable.)",
"debconf: falling back to frontend: Readline"
],
"stdout": …
```
=> [Linux] Fix Ubuntu official APT sources on ARM

autoinstall/Debian/10/preseed.cfg, linux/deploy_vm/templates/post_install_scripts/apt_install_pkgs.sh
Debian 13 autoinstall stuck at "Running preseed"
**Two issues:**
1) During autoinstall, it should bind the installer environment’s /cdrom to the target system’s /media/cdrom, but the installer did not do so
(if the ISO file is not mounted, the autoinstall will stuck)
2) CDROM APT source doesn't work even if manually mount an ISO file or use the mount command in a script to mount the ISO file.
**Resolution:**
bind the installer environment’s /cdrom to the target system’s /media/cdrom
Then, the autoinstall won't stuck.
Note:
For the issue 2, even if the CDROM APT source doesn't work, it won't 
affect the autoinstall. The packages will be installed from online repo.
**Test result:** 
Passed. (check GOSV-5206)
=> [Linux] Fix Debian 13 autoinstall stuck at "Running preseed"
